### ISSUE TITLE
Ice melts in arenas, doesn't get replaced when arena is finished.

### ISSUE THREAD

**Issue by AKPWebDesign** [garbagemule/MobArena#249]
Unlike blocks being placed in arenas, which get rolled back afterwards, ice that is already placed in the arena and turns to water is not rolled back. On a related note, water placed in the arena in general does not seem to roll back.

**Comment by Nesseley** [comment]
This is still a issue. 
- Ice blocks are melting even when arena isn't beeing used.
- Placing water while in arena on a lilypad, breaks the lilypad and doesnt replace when the arena finish.

**Comment by garbagemule** [comment]
Water breaking things should probably be an issue in and of itself. I have a feeling it's a pretty complex problem to solve, since water can wipe away quite a few different types of blocks, and I can't find a helper method in the Bukkit API that can be used to check if a block is "washawayable". I'll avoid doing anything preemptively and just fix the snow and ice issue for now :)
