### ISSUE TITLE
Error with Spigot 1.8

### ISSUE THREAD

**Issue by JordanAtFuze** [garbagemule/MobArena#254]
I am receiving the following error since I have started using Spigot 1.8, http://hastebin.com/sohazuyame.avrasm

**Comment by graywolf336** [comment]
@garbagemule Found some information about this recently, in 1.8 they changed it so that dogs/wolves attach a few more entities without provocation. Wiki says: [They will attack rabbits, skeletons, and sheep without provocation.](http://minecraft.gamepedia.com/Wolf#Behavior_and_appearance). So, I imagine that's why a skeleton would be targeted by a wolf inside the arena.

**Comment by garbagemule** [comment]
@graywolf336 Thanks! That'll definitely help :)

**Comment by garbagemule** [comment]
Reopen if this is still an issue.
