### ISSUE TITLE
Will MobArena (SpongeAPI) support mods?

### ISSUE THREAD

**Issue by Azatik** [garbagemule/MobArena#256]
Will MobArena (SpongeAPI) support mods? Cool arena would be.

**Comment by garbagemule** [comment]
To begin with, MobArena for Sponge probably won't have any functionality that it doesn't currently  have on the Bukkit platform. I intend to port the main functionality of the plugin to the Sponge platform to have something tangible, and to get familiar with the Sponge API, and then rewrite the plugin's core functionality in a much higher level of abstraction to allow for complex "extensions" like custom monsters, items, UI extensions, etc.

With Sponge's acquisition of Granite, however, I will most likely be focusing on getting things up and running in a vanilla-only setting at first, because I anticipate that people migrating from Craftbukkit or Spigot will prefer Granite to Forge.

**Comment by Azatik** [comment]
I think that people are divided two roughly equal camps: Granite and SpongeMod.
The number of forge-servers will be more.
Thanks for the reply.
