### ISSUE TITLE
Obsidian Bomb and Banner issues

### ISSUE THREAD

**Issue by DiscoveriesMC** [garbagemule/MobArena#271]
Obsidian bombs are breaking ladders, redstone, doors and a few other blocks. Upon blowing up they turn the block types I listed to stone rather than blowing them up. I have the arena setup to not take any damage to blocks.

Banners are also not restoring properly. If they are broken by the above glitch, they are restored to black banners rather than having their patterns.

I'm using the latest version of Mob Arena that is compiled with Spigot and I am using Spigot 1.8.8.

**Comment by garbagemule** [comment]
Is this with or without soft-restore? Because soft-restore is fairly broken at the moment, and should not be used unless your arena is very simple (no redstone stuff, no "tricky blocks" like skulls and banners and other things).

Are you using MobArena's own protection feature? Have you tried setting MobArena's protection to false and instead using WorldGuard or some other region protection plugin?

**Comment by ct-martin** [comment]
@DiscoveriesMC Hello, it's been a while since this issue was commented on, if this issue is still relevant please comment and tag me (with the @) so I can repoen it. Thanks!
