### ISSUE TITLE
Add support for shulker mobs.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#289]

**Comment by garbagemule** [comment]
What's special about shulkers? Why can't MobArena spawn them already?

**Comment by mibby** [comment]
You don't have to add it here?
https://github.com/garbagemule/MobArena/blob/dbff67866043a1ab76d2efd13e6a703003eb5671/src/main/java/com/garbagemule/MobArena/waves/MACreature.java

**Comment by garbagemule** [comment]
Since the conversion from enum to class, MACreature understands all EntityTypes (even the ones that don't make any sense whatsoever), so it'll support whatever mob types the EntityType enum contains:

https://github.com/garbagemule/MobArena/blob/dbff67866043a1ab76d2efd13e6a703003eb5671/src/main/java/com/garbagemule/MobArena/waves/MACreature.java#L22-L29

Go ahead and try it, let me know if they work.

**Comment by garbagemule** [comment]
Tried it out, and they work just fine.
