### ISSUE TITLE
Huge Bug: how to get classes armor easily.

### ISSUE THREAD

**Issue by dadee971** [garbagemule/MobArena#310]
Hi,
I'm using MobArena on a 1.10.2 Spigot Server.

Players can get the classes items easily.
They are lauching an arena, then, disconnect during arena.
When they log back they have the classes items in their inventories, instead on the inventories they've got before launching arena.
What an eay way to get a full enchanted diamond equipment, isn't it? :D

**Comment by AwesomeMan2812** [comment]
Ok, for me this ain't happening, you sure you have soft-restore set to true? Because I have no other idea what you could do.

**Comment by dadee971** [comment]
Hi,
What the soft restore can do about that?
A player go into an arena and he disconnect during arena. When he connect back he is wearing the classe  items.

**Comment by AwesomeMan2812** [comment]
Your config is fine, but it might be a plugin I have because when I disconnect from the game I don't have items in my inventory when I relog.

**Comment by slipcor** [comment]
I think this is caused by an inventory management plugin. This seems to be an issue on your end. If it was not, we would see a lot more traffic about this issue. I tried to verify this but

* leaving
* shutting down the server
* killing the game process

None of those things gave me the ingame inventory. Please double check that you are using the plugin version appropriate for your server version.

If it is caused by an inventory plugin, you can try restricting the join command to only the world, maybe it is a world change issue?

**Comment by garbagemule** [comment]
Please re-open if this is still an issue after v0.100. The join/leave process was completely rewritten for this release.
