### ISSUE TITLE
Players can get back into the arena by teleporting

### ISSUE THREAD

**Issue by leMaik** [garbagemule/MobArena#313]
We have a mob arena with chests and use geSuiteTeleport for teleporting, which has a `/back` command. When players (quickly) use `/back` after leaving the arena, they are teleported back into the arena.

MA already checks if the target location is a warp point, but it is (since the back location is the location the player was previosly teleported to, which is a warp point).

The good news is: I already fixed it, PR is on the way. :+1:

**Comment by garbagemule** [comment]
So the two attempts at solving the issue seem to be in vain. In the general case, we have four different cases with teleportation and arena regions:

1. Inside -> inside
2. Outside -> inside
3. Inside -> outside
4. Outside -> outside

Let's take a look at each case.

### 1. Inside -> inside

When players teleport within the region(s), it's _generally_ okay:

- when joining, to the lobby
- when spectating, to the spectator area (if covered by the region)
- from lobby to arena floor
- from arena floor to spectator area (if covered by the region)
- boss abillity "fetch"
- with ender pearl class items

It's not okay if that's using the /back command. The way to distinguish between people using the /back command and the other cases is pretty simple on the surface: just check if they are in the arena, and if not, disallow the teleport. The first PR had the right idea, but it didn't actually catch the "inside -> inside" case, only the "outside -> inside" case.

Players that aren't part of the arena should have the admin permission. When joining and warping to the lobby, the player will already be added to the lobby set, so it should actually still count as "in the arena".

### 2. Outside -> inside

Warping _into_ the region from outside is much more strict than warping within the region:

- when joining, to the lobby
- when spectating, to the spectator area (if covered by the region)

That's basically it. You're either joining the lobby or the spectator area.

There is one other case: join the arena from within the region (inside -> inside), then die and end up in the spectator area (outside), and then leave. That makes you someone who is currently leaving the arena, so maybe you aren't actually part of the arena, which means you would fall into the rejected category. The only way I see around this is to use a special "leaving" state of the player where they aren't part of the arena, but MobArena recognizes them as someone allowed to warp to their entry point or the exit warp.

### 3. Inside -> outside

Warping out of the region is okay in these cases:

- not part of the arena
- dying in the arena
- leaving the arena

It's not okay to warp out using ender pearls or other types of commands. To distinguish here, I think we may have to remove players from the lobby/arena/spectator sets before the teleport. That way, we can bunch them up with the "not part of the arena" players. Right now, MobArena warps players out first, and then "forgets about them".

### 4. Outside -> outside

Generally not a case we should worry about.

---

I think I can have a potential solution ready today, but because the teleport code is so mangled, I need some verification.

@leMaik if I make a new branch, can you help me test?
