### ISSUE TITLE
Is the 1.11 version compatible with 1.10.2?

### ISSUE THREAD

**Issue by ShayminKeldeo421** [garbagemule/MobArena#339]

**Comment by slipcor** [comment]
no. please use an older version or update your server :)

**Comment by ShayminKeldeo421** [comment]
Well that's shitty to just skip a version and not even support a version with a larger variety of plugins. Can we expect a 1.10.2 version at all?

**Comment by garbagemule** [comment]
The problem with supporting versions prior to 1.11 is the entity overhaul that's been done in Minecraft in 1.11. Since this overhaul completely changes the API for entities, there is no trivial way to support both versions.

It's fair to assume that people will eventually stop being lazy and actually update their servers instead of sitting on the same old version. So when you get around to updating your server, MobArena will already be ready for prime time, and you won't have to ask for an update. Until then, you can just use an older version of MobArena, which should work fine on 1.10 (with some caveats). 

Please consider the fact that you are using a completely open source plugin made by normal people, just like yourself, in their spare time. If you offered free coconut cookies, I wouldn't tell you that it's "shitty" of you to not offer chocolate chip cookies, just because I prefer those. Especially not if you also provided the recipe for free. You can take it or leave it, or you can engage in healthy discussion about pros and cons. Throwing a minor tantrum is a bit juvenile. Nothing keeps you from creating a fork for 1.10.2 yourself.
