### ISSUE TITLE
Hologram leaderboards

### ISSUE THREAD

**Issue by Sikatsu** [garbagemule/MobArena#355]
As the title says, leaderboards using holograms would be a much appreciated system instead of the signs (which don't update for me anyway)

**Comment by TheIntelloBox** [comment]
That would be great.

**Comment by garbagemule** [comment]
Is this still a thing? What are holograms? How do they work?

The only information I could find was based on NMS hackery.

**Comment by Sikatsu** [comment]
Hook into Holographic Displays perhaps?
Still a nice feature to have, signs are getting old.

Op zo 6 mei 2018 22:52 schreef garbagemule <notifications@github.com>:

**Comment by garbagemule** [comment]
Ah, I thought it was a Minecraft thing.

I don't think hooking into brittle plugins is the way to go about this. Leaderboards and statistics in general are pretty barebones in MobArena, and I think we can go a lot further by just introducing new events for other plugins to listen to, or by introducing support for a persistence layer.

Gonna close this for now since it's very much focused on specific plugin integration.
