### ISSUE TITLE
Explosions on entities causing block damage

### ISSUE THREAD

**Issue by GiraffeCubed** [garbagemule/MobArena#358]
Spigot 1.11.2
MobArena 0.97.5

Since recent updates, erxplosions in the arena from exploding sheep, creepers, obsidian bombs, and self introduced explosions have been damaging the terrain, allowing players and monsters to fall through in to areas that should be unreachable.

**Comment by slipcor** [comment]
Please www.pastebin.com your config. I tried to verify this yesterday, having seen your post somewhere else, but for me the protection still works. I specifically tested a default generated arena with protection and no other plugins installed.

Please check your server log for possible errors occurring during that time.

For me - with latest MobArena, 0.97.2 and latest Spigot, it works perfectly fine.

**Comment by GiraffeCubed** [comment]
My full config can be found here http://pastebin.com/9J6hYFUN
There's nothing in the logs that would hint at an error.

**Comment by garbagemule** [comment]
You have `soft-restore: true` for all your arenas. This is what allows the blocks to get damaged.

MobArena will clean it up after the match, but with this setting set to true it is your responsibility to encase your arena in a way that won't allow players to leave the arena region. That's why the auto-generated arena has a layer of obsidian below the sandstone.

Re-open if this is still a problem after setting it to false.
