### ISSUE TITLE
Some Metadata.

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#365]
Hello. Can you add some metadata tag for all mobs in arena?
For example, `entity.setMetadata("spawnedByMobArena", new FixedMetadataValue(plugin, true));`

I think this will be very useful for plugin developers (also for me at this moment), as it will make tracking mobs that are created during the game, thus other plugins will not affect them. For example, I have amplified creeper explosion, but I wouldn't want it at the arena.

Thanks!

**Comment by garbagemule** [comment]
Not a bad idea, but I definitely need to do some profiling to see how this affects performance.

If you're a little dev savvy, feel free to clone the repo and implement it yourself (it's likely just one or two lines of code) and try it out, see if it works and if its impact on performance is noticeable.

**Comment by molor** [comment]
Any news about this? I'm really need for some metadata on arena entities for now :c

**Comment by garbagemule** [comment]
No news from my side. It would be great if you (or someone else) could take a stab at implementing and profiling this, but it very much feels like a niche request.

In the meantime, you should be able to determine if a monster is a MobArena monster or not via MobArena's API. Since I don't know _how_ your creeper explosion amplification is implemented, it's difficult to suggest alternatives. If your implementation is a plugin, you can interface with MobArena directly. If it is some script engine, you can likely interface with MobArena either directly or indirectly via MobArena's own events. Chances are that you can make a "region filter" of sorts, in which case you should be able to just match that up with MobArena's region.

Since no one else has requested anything like this before, I imagine it's a non-issue in the vast majority of setups, in which case the commitment to a potential performance impact has to be well-founded. I highly suggest looking into alternatives unless you (or someone else) can do the performance testing leg work. I don't have much time on my hands as it is, and I prefer to spend what time I can spare on issues that benefit the most people, so any help would be much appreciated if anything is to come of this issue.

**Comment by garbagemule** [comment]
@molor Could you elaborate on how you're trying to interface with MobArena? Like, is it from a custom made plugin, from a script engine, etc.? I think that would help determine if there are potentially better solutions to the problem you're facing. I would prefer not to add unnecessary code to MobArena, but I'm also open to using metadata if it doesn't cause any major problems.

It looks like @slipcor is playing around with an implementation for this. If you could help him test out his work, that would probably be really helpful. At least then we'll know how viable the metadata solution is in terms of "functionality".

As for actually bringing it into the _current_ code base, I think the perfect time to do it would be in the Sessions Rework, since the concept of "spreading out" monster spawning is a sub-goal there. That would at least remove the worries about performance impact, because people could just say "only spawn 1 mob per tick" and that would likely solve all such issues. The second best time is any other time, like now, I guess :P

**Comment by molor** [comment]
> how you're trying to interface with MobArena?

In that case I'm using code similar to below to make my plugin lightweight as much as possible and don't depend [on the API] of other plugins.

```
@EventHandler (priority = EventPriority.HIGH)
public void exampleEvent(EntityDamageByEntityEvent theEvent) {
	if (theEvent.isCancelled()) {
		return;
	}
	if (theEvent.getEntityType() != EntityType.CREEPER) {
		return;
	}

	if (theEvent.getEntity().hasMetadata("isFromFurious")) {
		return;
	}

	// .. do some thing with creepers which not spawned from the "Furious" plugin
}
```

**Comment by garbagemule** [comment]
@molor According to some of slipcor's preliminary benchmarks, the `hasMetadata(String)` method is many times slower than asking the same question via MobArena's API. That's probably not what you meant by "lightweight", but I do think it's worth mentioning, especially w.r.t. "busy" events like EntityDamageByEntityEvent.

If I can find the time, I'll try to profile a bunch of sessions with and without metadata to see how much of an impact it has on performance. But I do want to focus on a couple of other things (and a new release with the current changes) first.

**Comment by molor** [comment]
I'm using MA API now.

**Comment by molor** [comment]
I don't need it anymore, but I think you can just make it can be enabled via configuration file (after a warning comment that it's bad for performance). And then the server owner will decide for himself whether it is important for him or not.
