### ISSUE TITLE
Colorcodes in announcements.yml brocken

### ISSUE THREAD

**Issue by Sandukhan** [garbagemule/MobArena#372]
Changing or adding new colorcodes to the announcements.yml seems to break the messages.
Instead of "&" i had to use "§" to make it work properly.

We are using the latest version of MA beta v0.98 (issue occurred in previous versions as well) 
runing on spigot 1.11.2 -4741400-c1aa859

**Comment by slipcor** [comment]
that is YML for you, there is not much MobArena or any other plugin can do about that ^^

**Comment by Sandukhan** [comment]
well according to the wiki, you should be able to change any formatting codes by using & in the announcements.yml. That does work at some places but not everywhere. For example:

I can change the string "arena-start-delay: Arena can start in &e%&r seconds." into "arena-start-delay: -->§3Arena can start in --> &a%&r -->§3seconds." but i cant use "&3arena-start-delay: Arena can start in &a%&r &3seconds." Thats just breaking the mesage later ingame and i dont think its was intended to do that.

**Comment by slipcor** [comment]
I disagree with you. I might be wrong, but if I judge how the string (and the internal processing) works, you have to enter the code after "arena-start-delay:" and not before that. If you change "arena-start-delay" to "&3arena-start-delay" you are basically breaking the "node" called "arena-start-delay" and MobArena cannot find it when looking for translations - you basically renamed the node.

But let's wait for the mule to comment on that

**Comment by slipcor** [comment]
I just verified it. You might have to surround the text with single quotes, this (whole line!) works for me:

```
arena-start-delay: '&acan start in &e%&a seconds.'
```

This turns the text green instead of white!

**Comment by TheComputerGeek2** [comment]
@slipcor you are close on your analysis of what happens when using the ```&``` character outside of quotes. I've dealt with this many times in the past.

What it actually does is tries to define an anchor under the label of whatever text is directly following the ```&```. This can later be used in combination with aliases or merges. But as far as I know, it doesn't rename the node.

Reference may be found here, on the snakeyaml documentation. https://bitbucket.org/asomov/snakeyaml/wiki/Documentation#markdown-header-aliases

Anyway, your listed fix is in fact the correct handling of this issue. The inclusion of the single quotes tells snakeyaml that the ```&``` is part of a string literal rather than an anchor.

**Comment by Sandukhan** [comment]
Ya with single quotes it works correctly,  other plugins i work so far dosent realy bother with quotes for formatting. Maybe add a hint in the wiki for stupid people like me ;P

**Comment by ct-martin** [comment]
@garbagemule @jflory7 does a note in the docs to use single quotes (& updating the default file to match) seem acceptable to you?

**Comment by garbagemule** [comment]
This has nothing to do with MobArena. It is entirely a "feature" of the YAML format and/or the snakeyaml parser. People typically run into these kinds of issues because of one lousy little symbol, or because of a combination of symbols that work "in a string" but not when they appear as bare values.

A perfect example is MobArena's item syntax. The string `I have 301:10 potatoes` is fine, but the value `310:10` on its own will get butchered by black magic fuckery in the snakeyaml parser and turn into some random number. There is a note on the item syntax page about this.

There's a perfectly reasonable explanation as to what happens, and there are inadequate, developer-centric explanations as to why the behavior was implemented - there was a choice of "human readable, machine understandable", but it came with the downside of "not human understandable".

Behold the one true configuration format: punch cards
