### ISSUE TITLE
Obsidian Bomb Dropping Block

### ISSUE THREAD

**Issue by CreedTheFreak** [garbagemule/MobArena#379]
Okay so we have a problem with our MobArena in terms of the Obsidian Block dropping after an Obsidian Bomb, this happens since we have some anti-explosive feature in a plugin somewhere and as such the Obsidian Block drops and our players are using those Obsidian Blocks to suffocate the Mobs that spawn in order to cheese the arena and get to really high levels without much effort. Hopefully there isn't some obvious solution to this that we have just missed, but I should have a pull request going up soon as to my solution to this problem. It could be that I am going about this all wrong in terms of the code, but hopefully it could be used to implement a better solution at least.

**Comment by garbagemule** [comment]
Looking at the pull request, I wonder why the heck the original source code breaks the obsidian block instead of just removing it. Perhaps a brain fart.

I'll close the pull request and commit a change so the block is removed instead of relying on the block item to be blown to pieces.

Thanks for reporting this, and thanks for your effort and consideration you put into the pull request! :)
