### ISSUE TITLE
Request: arena-level setting for arena completion rewards

### ISSUE THREAD

**Issue by TheBentoBox** [garbagemule/MobArena#393]
Often I want all players who beat an arena to receive a reward, and as far as I know there's no way to do it because there's no setting to give a reward when a wave ends, only when it starts. The only solution I've found so far is adding an extra unnecessary wave after the final boss and giving a reward when that wave starts, which isn't ideal.

It'd be nice if there was a setting for a reward to give to all living players when an arena is beaten. Either that, or another reward setting like `every` and `after` that gives the reward when the wave ends, not when it starts.

**Comment by garbagemule** [comment]
Hiya!

I took a peek at this, and it turned out to be a lot simpler than I thought it would be. Over the years, lots of people have pointed out the silly semantics of `after`. It should really be `on`, but it also kind of doesn't make any sense to reward people for reaching a wave instead of rewarding them for beating it.

In the build I just linked to over on #348, I also changed the behavior of rewards, so that rewards in both `every` and `after` are granted on the completion of a wave, rather than at the beginning of it. I tested a setup à la this one, and it works as you would expect:

    arenas:
      a1:
        settings:
          final-wave: 2
        rewards:
          waves:
            every:
              '1': $1
            after:
              '2': diamond

Please give it a go :)

**Comment by garbagemule** [comment]
The new 'after' behavior will be included in the next release :)
