### ISSUE TITLE
Command autocompletion

### ISSUE THREAD

**Issue by ct-martin** [garbagemule/MobArena#405]
# Summary

* This issue is a…
    * [ ] Bug report
    * [x] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: Have commands auto-complete when pressing the Tab key in-game or in the server command line

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [x] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**:
Autocompletion of commands (tab-completion)
**Does it need new or changed commands? What are they?**:
Nope
**Does this feature affect other parts of MobArena?**:
Shouldn't affect any.

# Details

There's an API for this

https://hub.spigotmc.org/javadocs/bukkit/index.html?org/bukkit/command/TabCompleter.html

**Comment by garbagemule** [comment]
I didn't know this was a thing. Sounds like a welcome change to the jungle of commands.

**Comment by jflory7** [comment]
@ct-martin This seems like a cool feature idea. 👍 Makes it easier for server administrators to not over-explain everything.

> Describe the issue / feature in 1-2 sentences:

Please don't forget the summary line when you file a new issue, though – that's helpful for getting an "at a glance" idea of this issue without reading the entire ticket or scrolling through all the comments. Could you edit that into the original comment?

> There's an API for this

Could you link to the API documentation? Where is this explained? I'm interested to read more. Please share any references and/or links to relevant documentation you know of for this.

**Comment by ct-martin** [comment]
@jflory7 The reason I don't fill out the whole thing is that I figured it was simple enough since and it's also done w/ all the vanilla commands. Apparently I was wrong. Also, if I filled out the entire thing it would be about two browser windows long / 1.5pgs printed-ish (and that doesn't include comments).

[The API is here](https://hub.spigotmc.org/javadocs/bukkit/index.html?org/bukkit/command/TabCompleter.html). I've used it before, but I don't have the code publicly posted online.

**Comment by jflory7** [comment]
> The reason I don't fill out the whole thing is that I figured it was simple enough since and it's also done w/ all the vanilla commands.

It's better to assume less of your reader than more. In this case, both garbagemule and I didn't know about the API. If you don't want to spend a lot of time explaining, linking to a reference or other reading material is helpful rather than making the project maintainer(s) dig for it.

It might seem like a silly thing, but I'm adamant about this because we, as core contributors, set the tone for everyone else. If we don't set a good example, then it's not good motivation for anyone else, if the core developers don't even bother with it.

> The API is here. I've used it before, but I don't have the code publicly posted online.

This is nifty. Never worked with it before, but seems like it will be a time-consuming task for all of the aliases the plugin uses. It might help me to see an implementation of this in another Spigot plugin, to see how they do it.

**Comment by garbagemule** [comment]
Tab completion would potentially reduce the need for the `pattern` bit in CommandInfo. I'm a bit worried that MobArena's commands architecture needs a bit of a rework for this to work, but it might be possible to just work tab completion into the existing command registration phase. Might be a good first issue for some of the more seasoned developers out there, but for rookies, I don't recommend it - there are so many commands to test :P
