### ISSUE TITLE
Fix deprecated calls to API

### ISSUE THREAD

**Issue by ct-martin** [garbagemule/MobArena#406]
# Summary

* This issue is a…
    * [x] Bug report
    * [ ] Feature request
    * [ ] Other issue
    * [ ] Question 
* **Describe the issue / feature in 1-2 sentences**: 
MobArena is currently using a bunch of deprecated API calls

# Background

Long-term benefits

### Bug report

* **MobArena version**:  Source in repo
* **Server version**:  N/A
* **Plugins**: N/A

# Details

77 warnings as per my IDE's count

**Comment by ct-martin** [comment]
@garbagemule if you'd like, I can work on this (just ping me here or IRC)

**Comment by garbagemule** [comment]
This is a typical "I'll get to it" thing. I think the majority of the deprecated calls have to do with item and block IDs, which is something that should just be phased out completely. But for backwards compatibility, it's important to retain some of the nasty calls. If they can be tucked away in a "scar tissue" package/utility classes, that'd be good. If they can be avoided completely, that's even better.

Feel free to dive into this @ct-martin - it should be somewhat trivial to verify that functionality doesn't break in most cases, but anything that has to do with soft-restore is a nightmare (just a heads up).

**Comment by jflory7** [comment]
Based on the above comments, I'll assign this to @ct-martin.

@ct-martin Do you have an estimated ETA for how long this work will take? Is there anything you have questions about?

**Comment by ct-martin** [comment]
I'm going to say end of next week as my initial estimate based on my
unfamiliarity with the codebase.

**Comment by garbagemule** [comment]
I would very much prefer one of two approaches to this. Both approaches split the task into multiple sub-tasks, and that's because I want to promote a workflow around the Single Responsibility Principle. This is something people often think about in terms of software architecture, but it can be applied in many other areas, e.g. issues (small, coherent tasks) and commits (small, coherent sub-tasks). The benefits of this is that it allows for extremely tight feedback loops, it keeps you focused, and the "burden" of continuous integration on the developer becomes an implicit part of one's workflow. Furthermore, it allows for extremely fine-grained version control (it's easy to revert individual parts of a bigger change).

The approaches:

A) Remove all occurrences of a dependency on a specific type, method, constant, etc. of the API throughout the entire code base. For instance, one such dependency could be on the ItemStack.getTypeId() method. By focusing solely on one dependency, the test surface is wide but very shallow, i.e. there are lots of different things that need testing after a sweep, but it takes almost no effort to test each thing, because there is likely only one affected code path.

B) Remove all dependencies on deprecated types, methods, constants, etc. of the API in a specific "unit" of the code base. For instance, one such unit could be ArenaImpl (perhaps the worst class in the entire project) or maybe the ItemParser. By focusing solely on one unit, the test surface is narrow but can be quite deep, i.e. there is often only a very specific thing that needs testing (not the case for ArenaImpl...) after a sweep, but it needs to be tested in depth, because its entire functionality may be affected.

Both approaches can be used for this issue, but they should not be used together in the same commit. Whatever makes the most sense in a given situation. So long as the commits stay focused. Refactoring is tedious work without automated tests, but it can be made less tedious by breaking it into smaller chunks of work that are less overwhelming.

Happy hacking!

**Comment by garbagemule** [comment]
... and it looks like we have a very clear starting point: https://www.spigotmc.org/threads/minecraft-1-13-what-to-expect.288714/

Block type IDs and scoreboards it is! :P

**Comment by garbagemule** [comment]
We need all of the deprecated item stuff to be replaced/fixed by next release to prepare for 1.13.

**Comment by garbagemule** [comment]
The remaining deprecated API calls are all about getting a Player reference by name. The given method is deprecated because player names are not guaranteed to be unique or matching across logins, but there is no alternative available in the API (aside from doing the search manually, which is a bit overzealous).

I'm gonna call it "good enough" for now :)
