### ISSUE TITLE
Offhand TNT does not deplete

### ISSUE THREAD

**Issue by GiraffeCubed** [garbagemule/MobArena#429]
MobArena classes with a limited amount of TNT can use infinite TNT if placed from the offhand. The TNT count regenerates shortly after placement.

* **MobArena version**: 0.99
* **Server version**: 1.12.2
* **Plugins**: MobArena

**Comment by ct-martin** [comment]
@GiraffeCubed You only listed MobArena under plugins, is this to mean you *only* have MobArena installed and _absolutely nothing else_?

**Comment by garbagemule** [comment]
This is very likely an issue with the way MobArena "repairs" weapons. Should be possibly to prevent/verify with the auto repair option set to false on a class.

Obviously, TNT is not a weapon, so it shouldn't auto repair.

Welcome to the April sweep.

**Comment by garbagemule** [comment]
I can't reproduce this, and nothing in the code seems to hint at this being a MobArena bug.

TNT is not listed as part of the repairable types that MobArena tries to repair on damage/attacking, and the repair code only changes durability, not item amount.

**Comment by GiraffeCubed** [comment]
When unbreakable-weapons is false, the TNT is taken from my offhand, but placed back in to my main hand. This is still exploitable, however. If you can't reproduce I guess I'll make my own fix.

Thanks anyway!

**Comment by garbagemule** [comment]
Ohh, auto ignite, of course. There might yet be something there then. I didn't test with auto ignite. I'll give this another whirl just to make sure I have all bases covered. In the meantime, could you please verify that my findings when auto ignite is off? Just to make sure we're on the same basis?

Would you be interested in taking a stab at fixing this issue in MobArena if it turns out to be a MobArena issue? Or what did you mean about making your own fix? :)

**Comment by garbagemule** [comment]
Confirmed!

**Comment by garbagemule** [comment]
Fix included in next release :)

Thanks for the bug report.
