### ISSUE TITLE
Polar bear boss does not use boss health

### ISSUE THREAD

**Issue by Pugabyte** [garbagemule/MobArena#433]
# Summary

* This issue is a…
    * [x] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: We created a boss as a Polar Bear but it dies in just a few hits, even if the health is set to "psycho" in the config.

# Background

### Bug report

* **MobArena version**: 0.99.1-SNAPSHOT
* **Server version**: 1.12.2
* **Plugins**: `PlugMan, AutomaticInventory, Murder, SimpleAPI, SidewaysLogFix, wget, AutoMessage, MinigameHandler, Chairs, ProtocolLib, CustomParticleEffects, bnCore, MVdWPlaceholderAPI, FastAsyncWorldEdit, PermissionsEx, FeatherBoard, WhatIs, Tab, ServerListPlus, PlaceholderAPI, OneWayBlocks, InventoryChess, ActionBar, VoxelSniper, EditableSign, Alerts, TimeLock, StopPushing, dynmap, WorldEdit, OpenInv, WorldBorder, BuycraftX, Votifier, LibsDisguises, eZProtector, Super_Elytra, SQLibrary, DotCommand, Vault, TitleAdvanced, LWC, Quake, PlayerPoints, ChestCommands, PlayerVaults, MyCommand, GAListener, Herochat, Trading, PlotSquared, WorldGuard, ASkyBlock, Prism, Essentials, HeadDatabase, LiteBans, Dynmap-ASkyBlock, VanishNoPacket, Plot2Dynmap, CustomEnchantments, ConditionalPerms, SimplePets, Multiverse-Core, Citizens, mcMMO, MiniaturePets, MobArena, EssentialsProtect, Multiverse-Inventories, EssentialsAntiBuild, ParticleHats, EssentialsSpawn, WorldGuardExtraFlags, Denizen, PurpleIRC, PreciousStones, HeavySpleef, EnjinMinecraftPlugin, PermHelper, KillerMoney, HolographicDisplays, Depenizen, VoxelSniperRegions, Multiverse-NetherPortals, MultiWorldMoney, Minigames, Minigames-Regions`

# Details

* **Stacktrace** (if applicable): N/A

* **Config**: https://github.com/Pugabyte/ServerFiles/blob/master/MobArena/config.yml#L1933-L2082

**Comment by garbagemule** [comment]
There's polar bears in Minecraft now? Cool.

This is likely a long-standing issue with Spigot's invasive max health settings. Can you try to change the max health of polar bears in the Spigot settings (I don't know how, I just know that you can) and see if that helps? Or maybe try with flat health values (just use numbers instead of the scaling health strings) from like 20 and upwards in various increments? Like, does this only happen if the final health value is greater than, say, 100, or 500?

I'll dig deeper at the end of April.

**Comment by FilidDamhsoir** [comment]
I just tested this with flat heath values, I tried 10, 20, up through 200.  No health bar at any level I tested.

**Comment by garbagemule** [comment]
Thanks for checking this @FilidDamhsoir :)

I honestly think it's a matter of Spigot/MC limitations more than anything. MobArena doesn't treat polar bears differently than other mobs, and I don't think it should have to. The max health is set to whatever the health value is, and then the health value is set to the same.

Was this on Spigot or Craftbukkit?

**Comment by Pugabyte** [comment]
(Filid is my Admin) We run Spigot 1.12.2, a build as of about 2 days

**Comment by Pugabyte** [comment]
My bad, didnt mean to close it

**Comment by garbagemule** [comment]
Alright, I'm pretty sure the problem is with Spigot.

In spigot.yml in the server root, change the value of `settings.attribute.maxHealth.max`to something big (but don't exaggerate with the zeroes). Maybe a hundred thousand (100,000). This is a value that's large enough that MobArena shouldn't feasible reach it (the formula for `psycho` health is the largest scaling function, and it's (#players + 1) * 20 * 60, so you'd need over 80 players in the arena to reach a health level that high.

Please let me know if this resolves the issue.

**Comment by garbagemule** [comment]
What kind of behavior from MobArena would be acceptable/expected here (assuming this is the problem)?

It tries to set a health value, but the underlying server implementation is disallowing it?

- Should the arena force end with an error explaining how to fix the issue?
- Should the boss be given a "best effort" health value (likely 2048, which is Spigot's default max health)?
- Something else?

**Comment by Nesseley** [comment]
Tested this now, and my polar_bear boss has tons of health. But I know from previous experiences that Spigot does mess with the boss health.

I like the suggestions you have, how about setting it to spigots max if its too high AND send a message til Console about "Boss polar_bear had too much heath compared to spigot.yml setting. Consider setting it higher to give bosses more health.
