### ISSUE TITLE
Kill the dog if the owner dies in the arena

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#452]
* This issue is a…
    * [x] Bug report
    * [ ] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
When a player that had a dog died, the dog should die aswell. As of now the dog is still in the arena killing things and making the arena easyer for the people still playing. (they can use the dog to scare skeletons)

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [ ] New config settings
    * [X] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
Kills the dog if the owner dies.
**Does it need new or changed commands? What are they?**: 
No
**Does this feature affect other parts of MobArena?**: 
No, I don't think so.

**Comment by garbagemule** [comment]
Currently, pets are removed when a player is revived or when they leave the arena. Since v0.100, players automatically leave the arena even if `spectate-after-death: true`, so this _should_ only be a problem with `auto-respawn: false`, because none of the clearing code will be run until the player hits "Respawn".

@Nesseley can you please confirm that this is the case in v0.100?

If so, this is a good first issue. The monster manager needs to be told to remove player pets when the player dies and `ArenaImpl#playerDeath(Player)` is called.

**Comment by Nesseley** [comment]
Sorry for the late response, but indeed this has been fixed and the dog now dissapears when the owner dies. 
Thank you so much for this fix!
