### ISSUE TITLE
Display boss health as a BossBar

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#459]
* This issue is a…
    * [ ] Bug report
    * [X] Feature request
    * [ ] Documentation request
    * [ ] Other issue
    * [ ] Question
* **Describe the issue / feature in 1-2 sentences**: 
Display the health of the boss as a bossbar, like enderdragon and wither have,

### Feature request 

* **Feature type**:
    * [ ] Arena configuration
    * [ ] Classes
    * [ ] Documentation
    * [ ] Economy integration
    * [ ] Leaderboards
    * [X] New config settings
    * [ ] Other (please explain)
    * [ ] Rewards
    * [ ] Third-party plugin support

**What does it do?**: 
Adds a healthbar for the boss, maybe even add option to "display bossbar for bosses: true/false"
**Does it need new or changed commands? What are they?**: 
No.
**Does this feature affect other parts of MobArena?**: 
No.

**Comment by garbagemule** [comment]
I'll let this one slip because this issue follows the template and the old one doesn't, but in the future, please use the search feature to see if there's already an existing issue that describes your request: #370

**Comment by garbagemule** [comment]
I think this should be pretty straightforward to implement. The Server class has a [createBossBar()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Server.html#createBossBar-java.lang.String-org.bukkit.boss.BarColor-org.bukkit.boss.BarStyle-org.bukkit.boss.BarFlag...-) method that returns a BossBar instance, which needs to be managed somewhere. A good place to manage it would probably be MABoss.

I wouldn't really deem this a good first issue since it requires messing around in quite a few spots in the code base. But, adventurers always welcome...

**Comment by garbagemule** [comment]
Implemented and released.
