### ISSUE TITLE
Translation of boss abilities

### ISSUE THREAD

**Issue by TheIntelloBox** [garbagemule/MobArena#472]
# Feature request

**Short description**

Could you add something to translate the abilities of the boss ? :D

**Implementation details**

It would be customizable, and it would affect the players. In fact, I'm French, and the message is : "Le boss utilise l'abilité: Living bomb". However, the ability can't be translated

**Additional info**

Thanks for adding this ! :D

**Comment by garbagemule** [comment]
_Note: I have removed the parts of the issue that ask for customization of the ability constants like blast radius for Living Bomb. This is a completely different matter and belongs in an issue of its own._

Okay, so the way MobArena's localization works is that there is a _fixed_ list of messages that can be translated. Because it's possible to add boss abilities dynamically, they can't possibly fit inside the fixed list.

I think the only proper way to address this is to rewrite the localization in MobArena to something that supports the dynamic nature of boss abilities. A rewrite has been on the drawing board for a while, but other things have been more pressing or more requested.

**Comment by garbagemule** [comment]
Technically #504 is the duplicate, but there's more info over there, so I'm closing this one instead.
