### ISSUE TITLE
Delay before join.

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#482]
# Feature request
In all the plugins I have to work with, it is possible to set the time during which the player does not have to move and take damage to teleport somewhere.

But MobArena doesn't have that. Because of this, on PvP servers during the fighting, players can write /ma j or /ma s and hide, keeping their inventory. That's bad, and I would be grateful if you could add the ability to change that.

**Comment by PrinceOfIonia** [comment]
This is actually a really good suggestion! I'm sure a configurable delay can't be that hard to make.

**Comment by garbagemule** [comment]
Is there a reason you didn't use the feature request template?

This sounds like it requires config file stuff, and it also sounds like there are existing plugins that do this. Please provide some examples of both.

**Comment by molor** [comment]
Yes, you will need to modify the `config.yml` file a bit. Examples?

https://github.com/xaniox/HeavySpleef/blob/master/bootstrap/src/main/resources/config.yml#L41
https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/config.yml#L72

**Comment by garbagemule** [comment]
Awesome, thanks!

So just to be clear, this is what you're asking for:

- Players Mike, Dustin, and Lucas run around in the wilderness of the server and decide they want to join a MobArena, so they all type /ma join.
- MobArena tells them all `[MobArena] Joining arena in 5 seconds...`
- After 2 seconds, a Creeper blows up right in front of Mike, damaging him, and he sees `[MobArena] Join aborted due to taking damage.`
- One second later, Lucas sneezes and accidentally presses the W key, moving forward, and he sees `[MobArena] Join aborted to due movement.`
- After a total of 5 seconds, Dustin joins the arena all by himself

Am I understanding it right? Is there a visible timer anywhere, or is it enough to just see that it's in X seconds, and X is configurable? And if it's 0, you insta-join with no timer message? Anything else I'm missing? What sort of messages would you like MobArena to send to the players?

**Comment by molor** [comment]
> Am I understanding it right?

Yes!

> Is there a visible timer anywhere, or is it enough to just see that it's in X seconds, and X is configurable?

`it enough to just see that it's in X seconds, and X is configurable`

> And if it's 0, you insta-join with no timer message?

Yes!

> Anything else I'm missing?

That's all. This is how it is implemented in other plugins, and this is enough for everyone c:

**Comment by garbagemule** [comment]
@molor can you come on Discord and test a build I've made with this feature?

**Comment by molor** [comment]
I'm not home right now, so I can't. But I believe it's done right. This ability cannot be done wrong :D
