### ISSUE TITLE
Legacy ID remapping for backwards compatibility with older versions.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#489]
See comments here.

https://github.com/garbagemule/MobArena/issues/488#issuecomment-414123953

**Comment by garbagemule** [comment]
@mibby @Ferocimo could you guys please verify that this is mainly an issue with rewards?

@PetricorCraft pointed out that it is possible to work around the issue by using CommandThings instead of ItemStackThings, i.e. granting the items via the /give command instead of via MobArena's item syntax. It _should_ also work for class items (but probably not armor) and upgrades.

If it's possible to completely work around the issue with commands, I feel like it would be a better approach than sticking legacy code into the item parser to accommodate a version most people seem to be moving away from, albeit slowly :)

Thoughts?

**Comment by Ferocimo** [comment]
Yes it's possible to work around the issue using command rewards, although I don't like that very much since it seems like a glitchy way of giving rewards.

**Comment by garbagemule** [comment]
@Ferocimo there is nothing glitchy about it. ItemStackThings are given to the players via the standard Bukkit API calls, which effectively do the same as the `/give` command. It's essentially as vanilla as it can possibly get. And since rewards are never taken from the players once granted, there is no issue with any of the revocation logic in the plugin. The only thing you definitely can't use it with is entry fees, and armor won't auto-equip because that's just how the `/give` command works.

If there is no functional difference on your end, there is really no reason to invest effort into this backwards compatibility. Eventually, 1.12 won't be relevant anymore, and I'd much rather push forward with new versions of the plugin than spend time on short-lived workarounds for people who haven't updated to 1.13 yet.

Don't get me wrong - I realize that 1.13 is a massive leap for server owners, and I respect the decision to stay on 1.12 for now (I'm much more comfortable with "stable" than "bleeding edge" myself). However, with the tiny amounts of time I do find to spend on the project, I prefer to push forward instead of retrofitting it to the past. The good news is that you'll likely have a bunch of new stuff to look forward to when you do eventually update.

**Comment by eiglow** [comment]
I'm on spigot 1.12.2 and having the same issue as #494. I tried changing it from `golden_apple:1` to `enchanted_golden_apple` but I still get the same error of `Failed to parse item`. I'm not sure how to do something like command rewards for this, as I'm using the golden apples as a class item.

**Comment by Ferocimo** [comment]
@eiglow If you want to use them as class item you have to use class chests. There's no other way on this version.

**Comment by garbagemule** [comment]
@Ferocimo and @eiglow If you can /give the item, you can put it in the config-file. You don't need to use class chests. The syntax for class items and rewards are the same.

**Comment by garbagemule** [comment]
Since 1.12 support is nearing its end, I'm gonna close this and hope that people have updated to 1.15 by now :P Feel free to reopen if it's still relevant.
