### ISSUE TITLE
Rework root-target boss ability

### ISSUE THREAD

**Issue by SXRWahrheit** [garbagemule/MobArena#490]
# Feature request

**Short description**

![2018-08-19 16_23_36- general - discord](https://user-images.githubusercontent.com/774463/44313332-4882fd00-a3cc-11e8-8a33-bd23800cf8d4.png)

**Implementation details**

Change root-target as described to allow players to aim and make the skill less punishing. `stun-target` or some such could be added to retain existing functionality.

**Comment by garbagemule** [comment]
Could be a good first issue.

One thing to keep in mind is that a player may already have one or more of these potion effects already active, and they shouldn't be overwritten by this ability. So, before applying the ability to a player, store their current "versions" of the three potion effects, then restore them when the root wears off.

**Comment by TheBentoBox** [comment]
I just want to note that, as of the latest versions of Minecraft which have been released since this was logged, players can have multiple potion effects of the same type applied at once, with the current strongest taking priority until it resolves, so there's probably no need anymore to store the old potion effect as described above. Should make it even easier!
