### ISSUE TITLE
Reimplement /ma j after game end.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#491]
**Short description**
You used to be able to use /ma j when the arena had ended and you were in spectator, now you need to /ma l til /ma j again. We want this feature back!
This is a struggle (with hi's from Ness, Wahr and probably Diamond)

**Implementation details**
This would work like this:
Play a game of mobarena.
Die - arena ends.
Use /ma j to join a new game of mobarena.

**Additional info**
We demand this, And I will bring pizza if you do this for us.

**Comment by garbagemule** [comment]
I want pizza, but I also want to not have to think about this and make arbitrary decisions, so please consider these cases and let me know how you guys expect MobArena to behave in each of them:

Steve just typed `/ma join a2` in the spectator area for arena `a1`, but...

- `a2` is currently running
- joining `a2` costs 4 dirt blocks, and Steve can afford it, but MobArena can't see his inventory as it is currently stowed away in the inventory manager (because spectating stores your inventory)
- there is a `join-interrupt-timer` of 5 seconds

How should MobArena behave in each of these cases? Specifically, the leaving of `a1` needs to happen, but when and how?

**Comment by Nesseley** [comment]
**a2 is currently running**
= Let Steve know that this arena is already running. You should also not be albe to join cross arenas.

**joining a2 costs 4 dirt blocks, and Steve can afford it, but MobArena can't see his inventory as it is currently stowed away in the inventory manager (because spectating stores your inventory)**
= Let Steve know that this arena can't be joined while in an arena. (If an arena cost blocks or other items you can't detect, it defaults to only allow join if not in an arena.)

**there is a join-interrupt-timer of 5 seconds**
= ignore the join-interrupt-timer. As I believe this is used for pvp, and there is no pvp in specator.

**Comment by PetrichorCraft** [comment]
Here's how I would expect it to happen:
Situation 1 - a2 is currently running:
a. It sends a message to Steve telling him that a2 is running, and he'll have to join another game or wait. 
Steve is still in the spectator area for a1.
b. Or, as Nesseley said, it tells him that he can't join a2 from a1. 
I don't really care between the two.

2nd situation:
Again, I agree with Ness. 
I'd tell Steve that it costs 4 dirt blocks, if possible. If not, just tell him that he can't join that arena from the spectator area.

3rd situation:
Yeah, I'd also ignore the join-interrupt-timer.

Okay, I pretty much just seconded what Nesseley said. xD But I started typing before I saw his answers (then reloaded the page when I saw the Discord message in #GitHub)

**Comment by SXRWahrheit** [comment]
Cosign @Nesseley's suggestion - this should be handled by only allowing a player to join an arena if not already in one.

**Comment by garbagemule** [comment]
What does it mean to be "in" an arena? From this issue, the spectator area doesn't count. How about the lobby?

**Comment by SXRWahrheit** [comment]
I think they should have to leave the lobby to join a different arena.

**Comment by garbagemule** [comment]
We back.
