### ISSUE TITLE
Investigate / rework teleport join sequence to improve state switching if going into spectating.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#508]
Paper dev 489 (Spigot 1.13.2)
MobArena v0.103.1

When you die in the arena, you are forced to spawn for a split second, sometimes up to two. Then you are brought to the spectator area. The join sequence seems to be ```Battle Location > Exit > Spectator``` instead of ```Battle Location > Spectator (if game is still on-going) > Exit```.

> It is intentional in the sense that to completely clean up any state for a player when they die, they first leave and then "rejoin" as spectators. It solved a bunch of hard-to-reason-about edge cases but unfortunately also introduces a "spec lag" on some setups.

However the main concern about the spec lag is due to my spawn being in its own world while all arenas are isolated in another. So it is teleporting players across world with a loading screen, then back into the arena.

> I suppose there could be a way around the teleport, but with the current join/leave architecture, a "join" is considered an atomic operation (so is a "leave"). The exit warp could be used as a workaround, but then you would lose the ability to "get back to where you were".

Unfortunately I won't be able to work around the issue by setting the exit location at the arena either since I have it so players aren't normally suppose to remain in the arena world.  They are only brought to that world when joining an arena or spectating, otherwise back to spawn or the overworld if the plugin supports it (teleporting back to old joining location). If I removed the defined exit location, the same issue would apply with players being teleported to a different world (old location), then back to spectate. :frowning:

**Comment by garbagemule** [comment]
Here's the "offending" commit from 8 months ago: https://github.com/garbagemule/MobArena/commit/b1c6b618279fd181799aeafdb041ad2d1775a585

I need to elaborate on at least one of the edge cases that the current approach solves.

Teleporting is one of the most overloaded "operations" in the Bukkit API, since it also covers world changing. And because it covers world changing, it also implicitly covers everything that changing worlds touches on, including gamemodes and inventories. The big challenge with resetting state is that if we don't reset "all the way", there has to be some sort of "breakpoint" in the join procedure that we can return to when we finally do want to go "all the way" (i.e. the `/ma leave` after we're completely done). Previously, the state management in the join procedure was very implicit and extremely flaky. Currently, it's very, very rigid and well-defined. I don't want to risk losing the well-defined property because it makes everything much easier to reason about (and harder to mess up), but it does require a bit of flexibility to support this kind of behavior.

**Comment by garbagemule** [comment]
@mibby I may have a workaround implemented for this. If you're still interested in this, please hop on Discord for a test build :)

**Comment by PrinceOfIonia** [comment]
Just tested the this recent build and unfortunately its even more broken than before.

**Comment by garbagemule** [comment]
@mibby I have a new build that seems to fix this on my end, but since I have no way of knowing how your server is set up and can't possibly replicate it, it would be great if you could give it a spin to see if the warping is still an issue. Feel free to hop on Discord and grab the current test build, or ping me if you'd like to walk through it with me.
