### ISSUE TITLE
Any plans to move to sponge?

### ISSUE THREAD

**Issue by Lordeath19** [garbagemule/MobArena#510]
Just wanted to ask if you are willing to create a port for mob arena to sponge, as all alternatives died out due to legal reasons, sponge is the only way to play forge with plugins.

Your plugin is one of the best plugins for a casual server and i would hate to miss out on it in forge

**Comment by garbagemule** [comment]
I was along for the Sponge ride in the beginning. Back then, it looked like Bukkit wasn't going to make it, and for that reason, the plan was to port MobArena to Sponge so that it could live on.

Bukkit prevailed, though, and a vast majority of servers stayed on Spigot's fork of Craftbukkit or switched to Spigot. Sponge is very clearly active, but it lost a lot of the initial momentum it had from the uncertain future of Bukkit and has become a sort of cult/niche thing instead of a successor. Porting MobArena to it means investing efforts into a very small (by comparison) target audience, and the efforts will not benefit existing users.

The problem with MobArena is that it is so heavily tied to the Bukkit API compared to other plugins that basically add abstract functionality with a tiny layer of integration with Bukkit (permissions plugins, economy plugins, report plugins, etc.). An abstraction layer that can support both Sponge and Bukkit is likely more work than a straight up rewrite for Sponge, and there's a huge risk it'll be very, very limited in terms of what is possible to do (lowest common denominator of the two APIs). So... 

- _Moving_ to Sponge and abandoning Bukkit makes no sense, because the current user base won't tag along.
- Building support directly in to the code base is a huge understanding that will likely create a host of issues and limitations that could very likely affect the existing user base.
- Rewriting MobArena from scratch for Sponge means splitting up my efforts on two projects, and I'm already pressed for time to work on MobArena as it is, so it'll likely mean a lot fewer updates. 

All in all, Sponge is just too much work that will benefit too few people. For me alone, that is. I would absolutely love to _assist_ with a Sponge implementation to create a new "MobArena family", but someone else would need to do the heavy lifting.

**Comment by Lordeath19** [comment]
Wait so you're telling me that spigot/bukkit actually do work with forge?

I was under the impression that sponge was a last resort that all forge servers had to fall to.

I would gladly use your plugin in forge if it's supported in craftbukkit/spigot

**Comment by garbagemule** [comment]
I have no clue about the Forge community and platform. Except that MobArena worked perfectly fine with Cauldron (even with custom mobs thanks to a bit of work with bloodmc), which was a Forge/Bukkit server.

If you run a server that implements the Bukkit API, then you should be able to run MobArena on it. But Sponge doesn't implement the Bukkit API. Maybe an adapter layer exists, but I don't know of it.

**Comment by Lordeath19** [comment]
Welp, thanks anyway.

I guess i got my answer
