### ISSUE TITLE
Starving in Lobby with `lock-food-level: true`

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#514]
# Bug report
**Short description**
You lose hunger if you run in the lobby region. (Even if the region is inside the arena-region.)

**Reproduction steps**
1. Setup an arena with `lock-food-level: true`
2. Join the arena.
3. run.
4. lose hunger.
5. If you start the arena you will have less hunger, and can't heal bc you dont have health for it. (food-regen: true)

**Details**
* **MobArena version**: 0.103.1
* **Server version**: Spigot 1.13.2

**Comment by garbagemule** [comment]
A lot of the in-session settings only work in-session. The lobby is in a strange spot because the arena isn't running when people are in the lobby, so the "is running" check always fails for the lobby phase.

https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L951-L961

Seems like this would be fairly straightforward to fix. Good first issue.
