### ISSUE TITLE
Fire Aspect not working in Mob Arenas

### ISSUE THREAD

**Issue by Kappable** [garbagemule/MobArena#519]
# Bug report

**Short description**

Mobs in the arena are lit then the fire immediately goes out if hit with a fire aspect enchantment.

**Reproduction steps**

1. Join an arena with /ma join
2. Hit a sign to pick a class with a fire aspect enchantment.
3. Hit a monster.
4. Watch the fire go out instantly.

**Details**

* **MobArena version**: (0.103.1)
* **Server version**: (Paper 530/Paper 514)

**Additional info**

Config: [https://pastebin.com/raw/y8j31a7F](url)

**Comment by garbagemule** [comment]
I'm worried that this is not gonna be fixable due to the way combustion works. I'll have to look into how combustion events are categorized. If we're lucky, combustion from a fire aspect enchantment can be distinguished from combustion by daylight.

Relevant part of the code base: https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L846

**Comment by a-l-e-x-0-6** [comment]
@garbagemule 
i found a fix to this, i wanted to do a fork and replace it but i'm new to Github and i don't know how to properly do it so here is the code:
```java
boolean sun = true;//this will be used to check if sun is faulty or not in the EntityCombustEvent
@EventHandler(priority = EventPriority.HIGHEST)
public void onEntityCombustByEntity(EntityCombustByEntityEvent event)
{
                sun = false;
}

@EventHandler(priority = EventPriority.HIGHEST)
public void onEntityCombustByBlock(EntityCombustByBlockEvent event)
{
                sun = false;
}
@EventHandler(priority = EventPriority.LOWEST)
public void onEntityCombust(EntityCombustEvent event)
{
            if (sun)
                 {
            	event.setCancelled(true);
                  }
            sun = true;
}

```
this code works fine alone but i haven't tried implementing it with MobArena because i have not installed Maven so i cannot compile MobArena.

it allows fire aspect to works while preventing combustion by daylight

**Comment by garbagemule** [comment]
@a-l-e-x-0-6 thanks for the contribution! Let's see if we can't get you up and running with the MobArena code base and Maven so you can try it out in the real context :)

**Comment by a-l-e-x-0-6** [comment]
@garbagemule i installed maven to compile MobArena and i did some testing,
["https://github.com/garbagemule/MobArena/compare/master...a-l-e-x-0-6:master"](https://github.com/garbagemule/MobArena/compare/master...a-l-e-x-0-6:master)
this works and fix the issue of fire aspect not working in arenas.

**Comment by garbagemule** [comment]
After a nice and productive Jam session today on Discord, we found that this is actually a bug in Craftbukkit/Spigot. The Fire Aspect enchant is only supposed to call EntityCombustByEntityEvent (two in fact), but it also calls an EntityCombustEvent, which it shouldn't. We found a very hacky way to get around the issue, but it is very clearly a bug in Spigot that will hopefully be fixed soon. I have reported the issue on Spigot's bug tracker here: https://hub.spigotmc.org/jira/browse/SPIGOT-5190

**Comment by garbagemule** [comment]
Fixed upstream in both [Spigot](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/8b09d98319f7c1d407d9db9bb053df0e2db4a6fe) and [Paper](https://github.com/PaperMC/Paper/commit/ef6823811b486615b67a33702b883823d0e5adb2)!
