### ISSUE TITLE
Level 2 / Extended Potions Via Config File

### ISSUE THREAD

**Issue by PetrichorCraft** [garbagemule/MobArena#520]
# Feature request

**Short description**

We should have a way to add level 2 and extended potions to classes via config file. (I think you were able to accomplish this in earlier versions, but support was dropped in... 1.12? 1.13? So this is only relevant for later versions)

**Implementation details**

I don't have a strong opinion for how this should be done, but I have ideas! I'm going to use Speed potions for my examples, but replace speed with whatever the ID is for whichever potion you'd like. 
These are the IDs I'd envision putting in the config file.
Extended:
splash_potion:speed_extended:1 (This would give 1 splash potion of extended speed)
potion:speed_extended:1 (This would give 1 drinkable potion of extended speed)
Level 2:
splash_potion:speed_2:1 (This would give 1 splash potion of level 2 speed)
potion:speed_2:1 (This would give 1 drinkable potion of  level 2 speed)

So, an example class would be:
  Archer:
    items: wooden_sword sharpness:1, bow power:3;infinity:1, arrow:1, potion:instant_heal_2:3, splash_potion:speed_extended:2, bone, cooked_beef:60
    armor: leather_helmet,leather_chestplate,leather_leggings,leather_boots

**Additional info**

Additional info? We love you, mule!

**Comment by PetrichorCraft** [comment]
I just noticed a miss-type, but I can't edit. I meant to say that potion:speed_2:1 would give 1 drinkable potion of level 2 speed.

**Comment by El-pika** [comment]
This is a really good idea, this would be easy to explain and to handle. But better do it this way
potion:extended_speed:1
potion:speed_2:1

This way you can also type potion:extended_speed_2:1 to get the better one

**Comment by PetrichorCraft** [comment]
I think that's a great idea, assuming it's possible!
I'm just not sure, since it would force MobArena to create a new type of potion (I think), as there aren't extended level 2 potions in Vanilla Minecraft. (At least not in the creative inventory, there may be another way to get them that I'm unaware of)

**Comment by El-pika** [comment]
My bad i was sure you could have an upgraded AND extended version of potions.

But in that case maybe just "add" the _upgraded for level 2 and _extended for longer.

**Comment by garbagemule** [comment]
Do we have any examples of how this is done in other plugins? I'd like for this to match some sort of de facto standard if there is such a thing - I much prefer "ah, of course, like in X" reactions than "wtf why is it not just like in X?" reactions.

**Comment by El-pika** [comment]
Here you have the Minecraft id :
minecraft:potion{Potion:strong_swiftness}
minecraft:potion{Potion:long_swiftness}

I'm quite sure everyone will find it easy enough to use !

Here is my source :
https://minecraftitemids.com

**Comment by graywolf336** [comment]
I just ran into this issue and couldn't convert some of my older classes to the new types and potions due to the lack of support for extended and level two potions. Almost do need extra data that says it is extended and is level two. 🤔

**Comment by garbagemule** [comment]
@El-pika thanks for the source and more info.

I would hate to introduce stuff like `{extended:true}` or something like that in the MobArena syntax, mostly because it doesn't really match the rest of the syntax.

Because the potions space isn't as large as I thought it was (Mojang seemed very proud of the idea of "hundreds or thousands of different possibilities" when they announced potions back in the day), it seems sort of okay to introduce some sort of exceptional parsing behavior for potions, where the data portion of the syntax can have "more stuff" in it.

However, it does look like it's possible for _some_ potions to both be stronger and have a longer duration. Consider Potion of Swiftness and Potion of Regeneration, which both exist in all four combinations (both level 1 and level 2 can have extended duration). This means that the syntax has to support both at the same time to cover all combinations.

Three approaches that all kinda make sense to me:

- **Prefixes:** Prepend `long_` for extended duration potions and `strong_` for level 2 potions, e.g. `potion:strong_healing:1` for a level 2 healing potion and `potion:long_strong_swiftness:1` for an extended duration level 2 swiftness potion.
- **Suffixes:** Append `_extended` for extended duration potions and `_upgraded` for level 2 potions, e.g. `potion:healing_upgraded:1` for a level 2 healing potion and `potion:swiftness_upgraded_extended:1` for an extended duration level 2 swiftness potion.
- **Hybrid:** Prepend `long_` for extended duration potions and append `_2` for level 2 potions, e.g. `potion:healing_2:1` for a level 2 healing potion and `potion:long_swiftness_2:1` for an extended duration level 2 swiftness potion.

Thoughts?
