### ISSUE TITLE
Re-check player inventory to respawn pet wolves if they have new bones in their inventory.

### ISSUE THREAD

**Issue by mibby** [garbagemule/MobArena#524]
# Feature request

I do not currently provide bones to my players as their class starting item before the game starts. Instead, I allow players to earn gold for surviving waves and be able to purchase certain items for upgrades.

If a player purchases a bone, the bone does not turn into a wolf the following round. Would it be possible to check for new bones so they may spawn as tamed wolves?

**Comment by FireController1847** [comment]
YES PLEASE!

I've been trying to make a "Pet Master" class, and they start with 3 dogs and very poor items. I want to be able to upgrade them to have more than 3 dogs, such as letting them gain a 4th or 5th dog. @garbagemule

**Comment by garbagemule** [comment]
I like the idea of upgrades including more than just items. I don't like the idea of "just checking for bones on every wave". It's needlessly clunky, adds to an already heavily overloaded procedure, and it's inflexible in the context of the sessions rework.

Perhaps the idea of "MobArena currency" needs to be explored as a core concept instead. Introducing currency and "shops" as a first-class citizen in the plugin would probably make it a bit easier to generalize the suggestion to something everyone can benefit from instead of setups that just happen to have a shop that offers bones.

**Comment by FireController1847** [comment]
@garbagemule Is there any way we could get a quickfix/temporary fix to determine if the upgrade has added bones to the inventory? I don't see how it could be much different from spawning them initially other than having to check every upgrade round. I do like the idea of a future overall core concept, but something that could simply fix this sooner rather than later would be amazing :P

**Comment by garbagemule** [comment]
@FireController1847 always doing "quick fixes" is what brought the code base into its current state. For every new hacky solution to a problem, the technical debt gets bigger, and the longer the necessary refactoring takes. You don't see how it could be much different because you're not intimate with the code base, but there is a good chance that it's much more involved than you'd imagine, or maybe the performance impact is much greater than you can accept. The proposed "quick fix" solves a very specific problem for a very niche kind of arena setup. In general, I prefer to spend my time on stuff that benefits the majority.

That said, I highly recommend forking the code base so you can take a stab at it yourself. If you stay close to the master branch, and if the changes are few, it might not be too difficult to maintain. And when the sessions rework is finished, perhaps you can refactor to something more generally applicable and submit a pull request :)

**Comment by Nesseley** [comment]
Maybe we should add a new setting to do this? 
Instead of checking for bones, we give out pets using the upgrade wave.
```
upgrade2:
          type: upgrade
          wave: 10
          upgrades:
            Knight:
              items: potion:instant_heal:4, cooked_beef:6
              armor: diamond_chestplate, diamond_boots
              pets: dog:1, cat:2
```
