### ISSUE TITLE
Some mobs not being aggressive at all

### ISSUE THREAD

**Issue by Fr0sto** [garbagemule/MobArena#543]
# Bug report

**Short description**

Some mobs (magma cube and ghast to be specific, I haven't tested more than the usual nether mobs) are not targeting players at all in arenas, regardless of reloading the plugin or changing configs or provoking them. _To be _clear__, all other mobs attack players in a perfectly normal manner, these are the only two I've had issues with.

Video proof: https://www.dropbox.com/s/l75rvrp2obl1xmb/mabug.mov?dl=0

**Reproduction steps**

1. Spawn waves with the two aforementioned mobs

**Details**

* **MobArena version**: 0.103.2
* **Server version**: PaperMC Build 97 1.14.2
MA config: https://pastebin.com/Z0Xv3TjG

**Additional info**

Originally (when I got the plugin) this did not occur, then it started occurring *sometimes* but would fix itself after a "/ma reload", and now it seems to be a permanent feature of my server. This happened over about a week.

**Comment by garbagemule** [comment]
This isn't a bug in the plugin. The last time the targetting code in MobArena was changed was over 7 years ago. The plugin does what it can to make mobs attack players, and it has been doing the exact same thing since the very first release. There is no other way to set mobs to attack players than the one MobArena already uses. Nearly all cases of mobs not attacking are due to either plugin conflicts (e.g. WorldGuard flags) or the server software being buggy (and Paper is notoriously buggy, so it's probably not helping in this case).

I say "nearly all", because slimes and magma cubes can't have targets (they don't implement the Creature interface, so they don't have a setTarget() method). Right before they jump, they decide where they want to go, and the internal server logic decides where that is. There's no way to change that in the API. I don't know exactly about ghasts, but I assume their logic is similar, given their slightly unorthodox attack pattern.

The "fix" of reloading has nothing to do with MobArena and everything to do with the fact that a reload forces you to run a new session, which is different from the one before it.

We can hope that the Spigot folks eventually change their minds about monster AI in the API. Until then, we're limited to what we have.
