### ISSUE TITLE
Tamed ocelots (not cats) Issue

### ISSUE THREAD

**Issue by sixamscrew** [garbagemule/MobArena#548]
# Bug report

**Short description**

We have a lucky blocks plugin called SuperLuckyBlock, which can give players a tamed ocelot (not a cat); the ocelot itself but tamed (behaves) like a cat. When players who have a tamed ocelot try to join an arena, error shows up in console.

**Reproduction steps**

1. Break a "SuperLuckyBlock" lucky block and get a tamed ocelot (not a cat)
2. Try to join an arena, e.g. /ma join mega
3. Error appears in console
4. Nothing happens in-game.
5. Players who don't have tamed ocelots can join the arena successfully

**Details**

* **MobArena version**: 0.103.2
* **Server version**: git-Paper-131 (MC: 1.14.3)
* **Stacktrace** https://pastebin.com/ztBVN4HK

**Additional info**

If I remove the players' tamed ocelots they can successfully join the arena after a /ma reload, however players were not too happy with the situation.

**Comment by garbagemule** [comment]
So something changed between 1.13 and 1.14. Ocelots are no longer tameable, which is why MobArena ends up throwing up over what it's doing. However, I'm afraid that it won't be possible to actually support the tamed ocelots on 1.14, because they are no longer "sittable" either. So any sort of interaction with the ocelots as "pets" is purely an illusion created by SuperLuckyBlock and would require some form of integration between the two plugins.

We can, however, take a stab at preventing the error!
