### ISSUE TITLE
Potion effects override each other and cancels the effect on duration end.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#562]
# Bug report

**Short description**
When a player has a infinite effect from the class, and throws a higher potion, the new potion applies instead. After the potion duration is completed the effect gets removed. 

**Reproduction steps**
1. Give a class `effects: speed`.
2. Give the same class `splash_potion:strong_speed:1`.
3. Start the arena. You should have effect `Speed **.**`. Now throw the splash potion. You now have `Speed II **.**`
In reality you don't have `Speed II` infinitely. You have it for the 1:30 the potion is supposed to last. 
4. When `Speed II 1:30` runs out you no longer have the speed of the class.

**Details**
* **MobArena version**:  0.103.3-SNAPSHOT (Test-build from Discord, posted Sunday 28th july.)
* **Server version**: CraftBukkit version git-Spigot-1981d55-da62a66 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)
* **Stacktrace**: none

**Comment by garbagemule** [comment]
The easy, crude way to fix this is to just remove the player from the list of affected entities if they already have the given potion effect type (or possibly only if the duration of the current effect is longer than the duration of the splash potion). The problem with that is that different levels of the same effect share effect type, e.g. Potion of Speed and Potion of Speed II have the same type: SPEED. In the given example, the player with the lower level speed effect from the class won't be affected by the higher level speed effect of the splash potion. **I will argue right now that this is the most stable, predictable way to fix the bug**, even if it isn't technically correct/expected behavior.

The hard, "correct" way to fix it is to introduce a type of tiered system where splash potions can take _conditional precedence_ over class effects if A) the splash potion amplification level is higher, and/or B) the splash potion duration is longer. What makes this approach **hard to vouch for** is that it introduces a super scary level of complexity.

Consider the following scenario: I'm playing a class with a **1-minute effect of Speed II**, we are **50 seconds into the session**, and my teammate just threw a **20-second Speed I** potion on me (i.e. we have a _partial overlap_ of 10 seconds, and in those 10 seconds, my class effect is stronger than the splash potion effect):

- Replacing the class effect with the splash potion means that I slow down.
- Extending the class effect duration means that the splash potion effectively becomes stronger than intended.

The solution is "simple" (it's still quite complex, but it sounds simple) at first glance: wait until the class effect ends, then apply the potion effect with a reduced duration to account for time passed. This one simple case is trivial, but what if more people start throwing splash potions? What if an upgrade wave adds a new effect to players of a class? The problem becomes infinitely harder the moment we expand the problem space to where the solution has to actually live. We run into a type of mix between [interval scheduling](https://en.wikipedia.org/wiki/Interval_scheduling) and [priority queues](https://en.wikipedia.org/wiki/Priority_queue), both of which seem like massive overkill for a problem this "small" (that's just my opinion of course).

Let's assume we have a fix that accounts for the above scenario. Now consider this slightly altered scenario: I'm playing a class with a **1-minute effect of **Speed I** (vs. II before), we are **only 30 seconds into the session**, and my teammate just threw a **20-second Speed II** (vs. I before) potion on me (i.e. we have a _complete overlap_ of 20 seconds where the splash potion is stronger):

- Replacing the class effect with the splash potion means that I speed up, but when that effect runs out, I've been cheated of the remaining 10 seconds from the class effect.
- Changing the amplification of the class effect means that the splash potion effectively changes the class effect for its entire duration.

This time the solution is along the same lines as before, but with a small twist: apply the splash potion effect, wait for it to finish, and then re-apply the class effect with the reduced duration to account for time passed. And again the problem becomes a matter of scheduling and prioritizing, because someone could throw a different splash potion while the current one is active, effectively extending the duration of the current effect, which means that our scheduled "timeout" that re-applies the class effect is now obsolete and needs to be revoked and re-instated with new information. Still a mess with a lot of edge cases that are just so difficult to tackle because of limitations in the Bukkit API and a tedious level of bookkeeping incurred in other parts of the plugin itself.

So would the incorrect but easy/stable/predictable solution suffice here?

**Comment by Nesseley** [comment]
this issue got fixed by mojang in 1.15.2.

See: https://bugs.mojang.com/browse/MC-169840
