### ISSUE TITLE
1.14.X Cat Bug

### ISSUE THREAD

**Issue by RWolfyo** [garbagemule/MobArena#563]
# Bug report

**Short description**

on 1.14.4 Classes with cat pet item (salmon for me) don't get their cat pet but instead a wild ocelot (Ocelots don't function as cat anymore in 1.14) and the console throws an error about trying to set an ocelot to tamed

**Reproduction steps**

1. Be on 1.14.X
2. Have a class with cat pet item and use it in the arena
3. You get a wild ocelot and an error in the console

**Details**

* **MobArena version**: v0.103.2
* **Server version**: PaperMC 1.14.4-154
* **Stacktrace**: https://pastebin.com/nP4sRdTL

**Comment by Nesseley** [comment]
I even get a error when trying to give a class a `salmon:1` and reloading the plugin.
https://pastebin.com/D2TQJkF4

As RWolfyo states, it spawns a wils ocelot. Not the new cats. 
**BUT:** you also keep the salmon, which isn't right?

**Comment by garbagemule** [comment]
Same problem that we were facing in #548. There's no simple way to fix the problem in 1.14 without breaking backwards compatibility with 1.13. This specific issue is even harder to solve because MobArena itself has to be the spawner and thus has to know what to spawn. There's basically no feasible way to avoid a check like "if on 1.13 spawn ocelot otherwise spawn cat".

**Comment by Nesseley** [comment]
Can we maybe add a setting cat: cod ? And remind people to ONLY use cod on 1.14? Or will that not work?

**Comment by garbagemule** [comment]
It's unfortunately not that simple. The problem is that in this context, the APIs for 1.13 and 1.14 are not compatible. If we target the 1.13 API there's no such thing as a cat, but if we target the 1.14 API ocelots can't be tamed (not in the literal sense anyway) and it breaks support for 1.13 entirely.

The way other plugins sometimes handle this is that they create abstractions, essentially making their own internal APIs for certain things, and then provide internal implementations of those abstractions specifically for 1.12, 1.13, etc. This requires a multi-project build structure that is much more complicated than the single-project structure MobArena uses.

The healthiest way to solve the problem right now is to remove support for cats/ocelots as pets entirely to prevent the errors, and then reintroduce cats (not ocelots) by bumping the minimum supported version to 1.14 once people have ditched 1.13.

It's very frustrating that the Minecraft internals and the Bukkit API have become so volatile, because it kills the stability of plugins by forcing them to either ditch backwards compatibility or come up with homebrew solutions to keep it. It's a horrible problem to have in software development because it cripples velocity.

**Comment by garbagemule** [comment]
I may have found a semi-solution to this problem.

I say "semi", because it's a solution that technically allows us to add any living entity as a pet in the `pet-items` map. The problem is that only Tameable entities will behave as pets and follow the players around. It's technically possible to spawn a zombie pet, but it will probably just wander around aimlessly, not attacking anything and not taking any damage (there's no surefire way to make any entity behave properly like a pet, so don't get your hopes up).

I haven't tested it out yet, but I have a build that _should_ allow you to change the `ocelot` in the config-file to `cat`, and it'll work in 1.14.

@RWolfyo would you be interested in helping test it out? If so, hop on Discord and ping me :)
