### ISSUE TITLE
Can't join arenas without recurring waves

### ISSUE THREAD

**Issue by chrismwiggs** [garbagemule/MobArena#566]
# Bug report

**Short description**

When creating an arena without recurring waves, players are unable to join the arena ("arena is not setup" message).

**Reproduction steps**

1. Create an arena with /ma create
2. Setup arena as normal, with /ma checkdata <name> returning "Ready to use"
3. Omit recurring waves (only use single waves)
4. Attempt to join arena /ma join <name>, appears as though arena is not setup.
5. Add recurring wave and the arena will finally allow you to join

**Details**

* **MobArena version**: 0.104
* **Server version**: Spigot 1.13.2-R0.1-SNAPSHOT
* **Stacktrace** No errors, just one info line: [17:37:57 INFO]: [MobArena] Found no 'recurrent' waves for arena earth, using default wave.

**Comment by garbagemule** [comment]
Thanks for the bug report!

This elusive bug has existed for quite some time now, and I finally figured out why it happens (quoted from Discord):

> Last time someone had it we found out that recurrent waves are required, but the part of the code that I thought was responsible has logic to work around it (that's why you get the INFO message). It's just not doing "enough" for the part of the code that does the checking when you try to join.
>
> Basically what happens is that if you have no recurrent waves, MobArena just generates a "catch all" wave for you that it uses whenever it can't find a match for the given wave number. Otherwise it uses the first recurrent wave you have defined as the "catch all". The problem is that the code that checks if the arena is ready to go still checks to see if you have any recurrent waves, which it probably shouldn't because it's already taken care of.

It _appears_ that the offending commit causing this issue is this one: 951e83cc55e30873d87a491cef5cdad6e9f4bf9c. Prior to this commit, the "catch all" wave that MobArena creates was added to the list of recurrent waves, but since that commit it doesn't. This means that the ["join logic" in ArenaImpl](https://github.com/garbagemule/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/ArenaImpl.java#L1510) fails, because part of it is checking to see if the recurrent waves list is empty or not.

I think we can solve the issue by just adding the "catch all" wave to the recurrent waves list as was done prior to the commit in question, _or_ by removing the check in ArenaImpl. The latter solution is probably more sound, because the WaveManager already makes sure that the arena is in a runnable state (and writes a log message that everything is fine), so nothing "bad" should happen.
