### ISSUE TITLE
How to aquire Toolbox

### ISSUE THREAD

**Issue by mrcoffee1026** [garbagemule/MobArena#573]
# Documentation

**Description**
I can't seem to find any information on how to acquire the Toolbox... which is what it needed for the golden tools that are used to set the regions.  I could use just a regular worldedit wand to make the regions without those but don't know what flags or special naming needs to be applied for the plugin to recognize them as arena regions.  There doesn't seem to be any documentation on a command to get them... so maybe this is something that automatically happens during set up, but there's no mention of when or how the chest appears or where it would be placed.  Any clarification would be helpful.

**Additional info**

**Comment by garbagemule** [comment]
The wiki pages are written in a hierarchical format similar to what you'll find in many software manuals and technical reports. This is why the table of contents at the top has nested lists on some pages. The deeper tiers assume that the information in the parent tiers has been read already.

Perhaps we need to revisit the general structure of the wiki, because the information you're looking for is right where it should be in this type of format. But if people aren't used to the format, we could maybe try a different format that has more redundancy. I just don't have good experience maintaining such formats because changes to a specific subject have to be made in multiple places.

**Comment by mrcoffee1026** [comment]
I understand the structure of the wiki, but this doesn't answer my question.  I still don't know how the toolbox is accessed and the wiki doesn't appear to mention that aspect of things at all.  Topics prior to this (specifically: Arena Setup) references tools that are supposedly contained inside the toolbox (for example: warp tool in the "About regions.." section), yet none of these sections mention a command for accessing the toolbox or generating one.  No sections prior to this mention it either.

**Comment by Nesseley** [comment]
You get the tools when typing /ma setup <arena-name>

**Comment by mrcoffee1026** [comment]
ah ok, thank you for letting me know.

**Comment by garbagemule** [comment]
I mean it literally says in the Setup Mode top section.

**Comment by garbagemule** [comment]
The very first paragraph:
>We will set up the arena using Setup Mode. When we enter Setup Mode, MobArena will temporarily store our inventory and give us a set of golden tools (the Toolbox), each with a different function.

The very next paragraph:
>To enter Setup Mode: Type `/ma setup <arena>`, where `<arena>` is the name of an arena. 

I would really love to know how we can make it any more clear without repeating those paragraphs all over the page. Should it be rephrased? Should it be somewhere else? I mean, the top section on Setup Mode tells you specifically that you get The Toolbox and that you have some new setup commands, and then immediately after how to enter and leave Setup Mode. Then it explains the commands, and then the toolbox, as subsections.

I don't want to sound rude, but it's so difficult not to call "impatience" on this one. I'm all for improving the wiki, but we have to trust that people can consume a structured document correctly, otherwise we have to abandon the format and just have one gigantic page with everything on it, and then tell people to "just Ctrl+F for keywords".

**Comment by mrcoffee1026** [comment]
Possibly moving these paragraphs to above the sections describing "Arena setup" and "Building an arena" as they are secondary steps to entering setup and acquiring a toolbox.  All other sections are written as though setup mode has already been entered and the tools are at your disposal.  Having it buried beneath all of that information made it seem as if it had been skipped entirely.

**Comment by garbagemule** [comment]
@mrcoffee1026 I'm so confused. Arena Setup is the wiki page, and Building an arena is one of the sections. Could you maybe give an example of what the TOC should look like? We currently have this:

```
On this page:
* [Building an arena]                 <-- Section about physical structure
  * [About regions, warps, etc.]
* [Setup Mode]                        <-- /ma setup <arena> introduced here
  * [Commands]                        <-- Sub section about commands in Setup Mode
  * [The Toolbox]                     <-- Sub section about the toolbox in Setup Mode
    * [Regions]
    * [Warps]
    * [Spawnpoints]
    * [Chests]
```

It doesn't make any sense to me to introduce `/ma setup <arena>` before introducing Setup Mode. You need to construct your arena before Setup Mode is relevant. Setup Mode gives you a set of tools and a set of commands, and they are introduced in sub sections of the Setup Mode section.

How would you structure it differently? Would it help to number the sections to make it more visible that you're in a sub section? Or is it the content that is lacking?

**Comment by mrcoffee1026** [comment]
If you don't want to fix it, just don't.  But your main page is structured aas this:
https://github.com/garbagemule/MobArena/wiki/Arena-Setup
Starts with Arena-Setup - Building an Arena; mentions toolbox... not how to get it, no mention of setup
About warps, regions, warps, etc... again mentions toolbox, not how to get it, nor setup.
It is only after you've been talking about setting up the regions and using the toolbox for 10 paragraphs that you introduce setup mode, but seeing a titled section "The Toolbox", I immediately go there to go looking for where i'd have expected to find this information since it's not put into a linear order, with it not being there, it appears to be missing.  This is where my confusion came from, and your initial response was no help suggesting I should have read the information in prior paragraphs when I simply hadn't read far enough into it to find the buried treasure about setup mode giving a different inventory with the tools available at that time.  I'm satisfied that the answer exists, I appreciate the time.

**Comment by garbagemule** [comment]
@mrcoffee1026 Are we looking at different versions of the same page? There is no mention of the Toolbox as a concept before the Setup Mode section. The Building an arena top section doesn't mention tools at all. The regions and warps sub section mentions the tools, but not the Toolbox.

If you jump straight to section 2.6.3 in a technical manual, it is generally assumed that the information in the parent sections 2.6 and 2 have already been read. In this case, you jumped from section 1.1 to section 2.2.1.

Your point about linearity is interesting. If you read the page in linear order, you will naturally progress through the information you need. But the page also acts as a "reference guide", allowing you to jump straight to the details, in which case the "technical manual" aspect applies. No matter how you look at it - and I truly mean no offence here - impatience is the reason you missed the information.

I'm all for improving the wiki, but when the claim is that "the information is missing" when it clearly isn't, there is not much I can do about it except ask for clarification. There's nothing "deep treasure" about Setup Mode. It literally has a top section on the page. If you don't want to help improve the wiki, that's fine, but when the information is there and in a structure that makes technical sense, what am I supposed to do to "improve" it? I'm not being arrogant here, I'm genuinely asking for help, not mud slinging.

---

On a more constructive note, I think this issue encapsulates some of the issues with the structure of the wiki _as a whole_. There is clearly a need for a more complete, cohesive, self-contained, linear, and hand-holding page, which goes through _just_ the motions necessary to get up and running. A dedicated _Getting Started_ page. It can contain references to other pages throughout the guide, and include links at the bottom to "next steps". We could then _also_ have a page that is dedicated specifically to Setup Mode, rather than it being mixed in with the act of building an arena structure, which could  also have its own page.

Note that the wiki home page already has a _Getting started_ section that I think sorta kinda has the right idea going, but I definitely think it deserves a dedicated page with "shortcut" pieces of information.

**Comment by mrcoffee1026** [comment]
Picking nits here on semantics is all this is at this point.  True, the section about setting up the arena, the floor, the spectator area, etc... do not actually mention the toolbox, but you need the tools to perform each and every one of these tasks.  Again, in a linear order, I have to read through all of the detail of what I can do with the item before finding out how to acquire the item.  It is discussed briefly in a separate section... then the expected location that is actually titled "the toolbox" doesn't cover that information.  Call it impatience if you want, or that you need to 'hold my hand" through everything, fine... I just feel that the step that covers the "you need this item to do anything and have to do this step before you can set up your arena, define points and containers" and so on... might come before all of the paragraphs explaining those details.  Again, I'm sorry I missed it, but I'm surprised more people don't have this question from the get go.

**Comment by garbagemule** [comment]
@mrcoffee1026 I don't see how it's nitpicking semantics at all. I'm trying to figure out how to improve the documentation, which means assessing what information is where and potentially moving stuff around. If the words on the page are not conveying the information they need to, we have one problem. If the reader is expected to read the words on the page and they don't, we have another problem. The former can be solved by just adding information, the latter is much harder, because it involves backtracking. I'm not asking you to "tell me what you did" because I want to point fingers, but because I need to understand your path through the wiki. I'm not holding back answers because I'm an arrogant asshole who thinks he is infallible, but because I want people to be able to find the answers themselves (again, not because I don't want to help, but because it's a huge bottleneck and a major deterrent if people can't get up and running without talking to someone first).

As for the actual content, you're _not_ reading through "what you can do with the item" in the first section, you're reading through the terminology of arenas, and the tools are mentioned at the very end of each paragraph as forward references (albeit with no links). But perhaps that's part of the problem then. Maybe the tools shouldn't be mentioned at all before the Toolbox section if it urges people to skip the main section about Setup Mode. In a strictly linear read-through, you'll meet the command before you meet the Toolbox.

And just to be clear: when I say that we need _Getting Started_ content that is "complete, cohesive, self-contained, linear, and hand-holding", it is not an attack on you. It's an observation that because the wiki is fragmented, people are required to jump around from the start. If there is a single page that takes you through the absolute basics in a completely linear fashion, you won't have to jump around. You can stay on that page until you have a feel for everything, and then move on from there when you're ready to start customizing.

As someone who just went through the motions, you're a pretty solid candidate to capture them and write them down. Even an ordered list of topics to cover would be a huge help.

**Comment by mrcoffee1026** [comment]
Well, again, I think the simplest solution (for me) might have been to just have seen the Setup Mode information (and that in regards to the toolbox within) placed prior to the Building the Arena section... as virtually every paragraph within references things I need the tools to do.  Alternatively, you *could* hyperlink every mention of tool or toolkit to the "The Toolbox" section... not in its current form - of course.  But as I'm at least vaguely familiar with how wiki's work, this is where I went to find the answer to this exact question, and was rather stunned to not find it there.  Since paragraphs prior also mentioned the tools and not how to acquire them, this led me to believe this to be an error of omission.   I also feel that discussing particular regions have very little context if you're not already in setup mode, so it seems oddly out of order to mention this after those details instead of before.  It's as if the first ten paragraphs on this page were intended to be an overview... from some philosophical perspective, not with any real application.  Like if the wordedit wiki went into great detail about what a person might do with a region selection without ever mentioning the wooden axe or that there were commands to specify points.  It might be an interesting read, but would not provide any assistance in setting up and using the plugin.  This is effectively how this page begins... and goes on in that manner for ten paragraphs before sneaking in the bit about setup mode and that bit about swapping inventory... which is a massive shock if you don't know it's coming so might be something you'd want to call attention to.  Anyway this is my opinion on the matter, the information - as you say - is indeed included on that page, it is just not where I would have expected to have found it on that page.
