### ISSUE TITLE
Add lobby ready state to sign templates

### ISSUE THREAD

**Issue by Bobcat00** [garbagemule/MobArena#593]
# Feature request

**Short description**

Adding a new state for the sign templates would allow greater flexibility in the use of signs. This would be an additional enhancement of #591 

**Implementation details**

Currently, the only state while players are in the lobby is _joining_. Adding a new state, _ready_, when all players in the lobby are ready, would allow additional flexibility in what could be done with signs.  For example, a sign could display a red 'Not ready' indication along with the names of the not ready players, and a green 'Ready' indication when all the players are ready.

Use of the _ready_ state in the template definitions would be optional.  _Ready_ could inherit its values from the _joining_ template definition.  If the template did not use the _ready_ state, it would continue to follow the _joining_ definition after all players are ready.

Overall, the states would be _idle_, _joining_, _ready_, and _running_.  The state could go "backwards" from _ready_ to _joining_ if another player joined the lobby during the arena start delay.

Although I want to use this on my server, I admit it's of limited utility, as _ready_ is only active during the arena start delay period.  I'd be interested in other peoples' thoughts on this.

**Additional info**

Is there any sort of test suite for the sign templates?  How do we know the change doesn't break existing templates?

**Comment by garbagemule** [comment]
Excellent!

There is no reason why this shouldn't be possible. I think it's fairly easy to check if all players are ready (the logic to do so is already in ArenaImpl, and I think it's just checking to see if `lobbyPlayers.size() == readyPlayers.size()`.

The signs package is actually one of the more thoroughly tested parts of the code base, but a certain someone deleted them all :P

**Comment by Bobcat00** [comment]
I already have this working. Need to update it to include the other changes after they're done.

**Comment by Bobcat00** [comment]
Take a look - https://github.com/Bobcat00/MobArena/commit/77a3d8f4204c48d0369c9dad8ae599f05634cd0e
But I still couldn't get your tests to work with Eclipse.

**Comment by garbagemule** [comment]
Your changes look really good. I like that the blast radius is fairly small. It should also be fairly easy to add some tests to cover the variations.

I have only three (admittedly nitpicky) comments:

- The `// inherit from joining` comment needs to go above the statement instead of next to it. I think it makes sense to also add "instead of base" to clarify that it's a completely intentional variation of the pattern in the other checks.
- The `// ready is optional` comment is positioned just fine for the way the code is structured, but it does look like the comment belongs to the line below it (I guess that's a downside of prohibiting "side comments"). Perhaps it makes sense to make a more elaborate comment above the `if (base == null) {` check, explaining that if the base is null, the three primary states (idle, joining, running) are mandatory, and ready is optional. In other words, perhaps this little change is enough of a variation that the whole block needs to be documented instead of just that one line.
- The check in RendersTemplate should be inverted, such that if non-ready players is empty, return `ready`. This is very much in the deep end of my code style preferences, but the rationale is that we enter the branch because of the mandatory `joining` state, and `ready` is a special variation of that state, so it should be the early return rather than the "default".

**Comment by Bobcat00** [comment]
The optional/inheriting comments are there to prevent someone in the future from looking at the code and saying, "Oh no! He forgot to include a check for ready!" and then breaking the code.
