### ISSUE TITLE
Allow pet nametags to be configurable

### ISSUE THREAD

**Issue by Bobcat00** [garbagemule/MobArena#595]
# Feature request

**Short description**

As you can see in the attached screenshot, pet nametags using the displayName can be ridiculously long.

**Implementation details**

At the very least, change it to use playerName. You could make it controllable via the config file. Want to get fancy, make a whole string with variables and color codes.

![2020-01-10_21 45 34](https://user-images.githubusercontent.com/3617206/72197737-af0a2000-33f2-11ea-84f0-ed7de4128061.png)

**Additional info**

It's hilarious watching skeletons run away from the dogs.

**Comment by garbagemule** [comment]
This is a little controversial.

On some servers, the display names are used for nicknames. So maybe on a server I would just be known as "mule", so I'd change my display name to that. On another server I might be known as "Frank", so that's the name I'd like to see on things associated with me.

I think it would be weird to see "garbagemule's pet" run around next to a player named "Frank".

Display names are specifically chosen for certain parts of the plugin because some people said that the player name was wrong to use. So it seems like we're stuck between a rock and a hard place. I think it would be necessary to make it configurable to not step on anyone's toes. I'm sure someone will want to translate it too.

Can't the length issue be solved by limiting ranks to the chat and using "just names" for display names? I've seen that before.

**Comment by Bobcat00** [comment]
I do something like this in a couple of my plugins:
```
# Supported variables are %player%, %displayname%, %version%, and %server%
notify-string: "&6Player &c%player% &6is using version &c%version%"
```
The default could be display name and it would be entrely backwards compatible.

Just think of the poor dog having to carry around that huge billboard on his back!

**Comment by garbagemule** [comment]
I just want to follow up on this to summarize some of my thoughts about the _how_ (implementation), because I think there are enough _whys_ to advocate that configurable pet names should be a thing.

Originally the suggested solution revolved around placing pet name templates in `global-settings`. The issue with global configurations is that they don't allow for any sort of per-arena or per-class variations, and if there's one thing we've learned about arenas and classes, it's that they tend to be very thematically different.

The current solution in PR #597 moves the configuration from `global-settings` into `classes`, which partially solves that limitation by allowing each class to have a different pet name template. This means that a class called Police could have wolf pets called e.g. `<player>'s K9`, while a class called Shaggy could have a pet wolf called e.g. `Scooby Doo`. However, if we wanted to have a Circus themed arena where all pets are called `<player>'s assistant`, that wouldn't work. The question is whether or not this is actually desirable.

Perhaps the best approach is to start off with pet names configured at the `global-settings` level, and if someone wants per-class names, we can introduce class-level _overrides_. And if then someone comes along and wants per-arena names, we could introduce arena-level per-class overrides. Here's an example:

```
global-settings:
  pet-name: '<player>\'s pet'

classes:
  Police:
    pet-name: '<player>\'s K9'
  Shaggy:
    pet-name: 'Scooby Doo'

arenas:
  circus:
    pet-names:
      Police: '<player>\'s assistant'
      Shaggy: '<player>\'s assistant'
```

We could perhaps even have a sentinel `all` key in the arena-level overrides to minimize typing if someone really just wants to override everything for an arena. The priority would then be the following:

1. Arena-level per-class override.
2. Arena-level `all` override.
3. Class-level override.
4. `global-settings` base definition.

I think we should just start out with the `global-settings` base definition to keep things simple, but in case the remaining suggestions come along, we have a plan of execution.

I'm still not sure about implementation details. I feel like the pet spawning logic could be reworked as a general sort of cleanup-for-reuse effort, but it might not be necessary yet.

Thoughts?
