### ISSUE TITLE
Request Console Command when entering and/or leaving Lobby/Arena

### ISSUE THREAD

**Issue by VimaMT** [garbagemule/MobArena#598]
# Feature request

**Short description**

Please provide option in config file for entry and exit console commands. Worldguard and other plugins prevent people from performing commands inside a region. However, if a player is already in /god mode, those other plugins do not disable it upon entry into the Arena.

A configurable console command should allow server operators to handle these types of situations using commands which are provided by the other plugins.  The command upon entry is more important.  The command upon exit is just a "nice-to-have."

**Implementation details**

A per-arena setting would be created in the config file for entry console commands.  One example might be:   /cmi god %player% false        ...  setting god mode off for the player who is entering the arena.  Note that a place holder is involved.

Although I cannot think of a reason, an exit-type console message may be beneficial to someone in the future.

**Additional info**

I have seen comments in this issue section concerning god mode issues, and I have seen some comments in discord about it.  I have not seen any resolutions.  God mode is likely not the only player setting that needs to be negated.  A console command would be beneficial for almost any setting like this, provided the other plugin allows administrative intervention.

**Comment by VimaMT** [comment]
I should have stated, "Although I cannot think of a reason, an exit-type console command may be beneficial to someone in the future."

Sorry about miscommunication.  And thank you for the great plugin.

**Comment by garbagemule** [comment]
This is not a bad idea at all. However...

When a player joins an arena, MobArena takes the following steps:

1. A cancellable event is emitted via Bukkit's event bus. If cancelled, MobArena aborts the player join.
2. If the arena has an entry fee, the fee is removed from the player's holdings (balance, inventory, etc.).
3. All of the player's nearby pets are told to sit.
4. The player is teleported to the lobby (possible world change).
5. The player's gamemode is set to Survival (possible gamemode change).
6. The player's inventory is saved, then cleared.
7. All of the player's current potion effects are stored, then cleared.
8. The player's "flying" and "allowFlight" flags are set to false.
9. The player's health, hunger, and experience are all saved, then "reset".
10. The player's local time is changed according to the arena settings.
11. If a default class is set, the player "selects" that class.

Before (or after) which step should the configured commands run, and why? Some of the steps have side effects in other plugins, such as world and/or gamemode changing, and inventory clearing might have side effects on the next tick (something MobArena can't do anything about).

As for addressing the problem _right now_, I'm afraid it's not going to happen in MobArena before the sessions rework, since this is very deep into sessions territory. It's too much of a major change to justify implementing now when the whole sessions functionality is being rewritten.

There may be workarounds, though. The issue of "god mode" has been solved by other people before without changes in MobArena, so I'm sure there's a way to solve it for you as well. I just don't know how these plugins work.

Perhaps you can run a specific command when someone changes to a specific world? Or disable god mode in a specific world? In that case, having the arena is a separate world might be enough.

Because of the ArenaPlayerJoinEvent, it is technically possible to implement this in an addon plugin or with a server-side script (Denizen, Skript), so that's another way around it.

Maybe you can solve the issue by using command things as an item for every class, i.e. something like `cmd:/cmi god <player> false`.

**Comment by garbagemule** [comment]
Closing this in favor of #678, which covers a bit more ground than this issue does.
