### ISSUE TITLE
Incorrect Entryfee results in Internal Error 

### ISSUE THREAD

**Issue by EchocallingEarth** [garbagemule/MobArena#599]
# Bug report

**Internal Error if entry fee enter incorrectly**
When I enter the entryfee if I fail to properly provide the cost $10 and instead use 410(missing shift+4 or $) and do not realize it. The plugin throughs an internal error and no longer recognizes the arena. 
The first screenshot is the MobArena EntryFee entry line
![2020-01-17_19 57 56](https://user-images.githubusercontent.com/47970978/72655870-7a074b80-3965-11ea-846d-118a558ae913.png)
This next screen clip is the internal error
![2020-01-17_19 58 46](https://user-images.githubusercontent.com/47970978/72655877-89869480-3965-11ea-8a93-7c5a46c293c6.png)
This next image shows that the arena named Test is no longer visible
![2020-01-17_19 59 16](https://user-images.githubusercontent.com/47970978/72655908-a753f980-3965-11ea-8af9-d31ae015d105.png)
IMPORTANT: At this time I did a restart because I was unable to determine error as the arena was no longer visible ingame The images that follow and details are post restart
Upon restart, I attempted to locate the arena ingame and it still does not show. So I manually entered the information as follows:
/ma setting test entryfee $10
at which point the plugin send in chat "Failed to parse entry fee of arena test: 10
See image
![2020-01-17_20 03 08](https://user-images.githubusercontent.com/47970978/72656035-af606900-3966-11ea-9404-add807c6bff8.png)

Entering any other request via chat before fixing the config related to the arena named test will throw the same message as above.

Please note the following images are to show me fixing the config and reloading and then showing that the arena in question is visible.
Config error
![ma error](https://user-images.githubusercontent.com/47970978/72656343-a5d80080-3968-11ea-8b1b-2095ffa7f8ed.PNG)
Config error fixed in config
![ma fixed](https://user-images.githubusercontent.com/47970978/72656370-ca33dd00-3968-11ea-93af-6d622c23d526.PNG)
Reloading plugin in game
![2020-01-17_20 32 02](https://user-images.githubusercontent.com/47970978/72656376-d881f900-3968-11ea-9890-6c0d4a125b68.png)
After reloading the arena in question is now back and able to be worked with.
![2020-01-17_20 32 15](https://user-images.githubusercontent.com/47970978/72656396-efc0e680-3968-11ea-8495-27ca875ce5b9.png)

**Reproduction steps**
Create an arena using normal steps.
1 - /ma addarena {name}
2 - /ma setup {name}
3 - stop (this is what I use to exit the setup mode)
_After the arena is created and considered ready to use._ 
/ma editarena {name}
/ma setting entryfee 10
↑This should throw the internal error.↑

**Details**
This is the error log when this happens:
https://pastebin.com/aPU6iTES

[MobArena] Loading MobArena v0.104.2
 This server is running CraftBukkit version git-Spigot-492a779-e7202cd (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT)

Any info I can provide I will gladly do so to help fix this error.

**Comment by garbagemule** [comment]
Thanks for the detailed bug report! Awesome work!

I'm labelling this as an enhancement, because technically there is no bug here, but rather poor user experience. That doesn't mean we shouldn't do anything about it, of course :)

Using `10` as the value for the entry fee doesn't make sense, because entry-fees are "things" just like any other "thing". MobArena can't assume that it's economy-related. The error makes sense, and the failure mode makes sense.

However, it seems like the `/ma setting` command was left out in commit 2081405d3bf45ca97d98913bbe1f558b3b3afe4e, where the startup logic and error handling was reworked. The part of the command that [reloads the config-file](https://github.com/garbagemule/MobArena/blob/86be8bdfbd94d55f1fa8fe2035b8ec04ace424a6/src/main/java/com/garbagemule/MobArena/commands/setup/SettingCommand.java#L90-L92) doesn't catch config errors, which means the errors propagate out of the command handler and become "internal errors". We should catch the error in the command or in the main command handler and deal with it there by printing the same kind of message `/ma reload` prints for consistency.
