### ISSUE TITLE
(Elder)guardian Laser bug

### ISSUE THREAD

**Issue by Ghmmy** [garbagemule/MobArena#601]
# Bug report

**Short description**

When I join the arena and a(n elder) guardian spawns and tags a player with his laser, the laser wont disappear after placing a block between the player and the guardian (the player wont get hurt after he's behind the block, its just that he laser wont disappear). This causes the guardians to attack the player constantly after the player moved away from the block/is back in the vision of the guardian.
for a better explanation, I made 2 videos of it:

MOBARENA: https://imgur.com/a/3o5bmJm

VANILLA: https://imgur.com/a/H13ClaK

**Reproduction steps**

1. Add the guardian to the monsters in the config 
2. Join the arena
3. wait for the waves to spawn a guardian
4. get tagged by the guardian
5. place a block between you and the guardian, so that the guardian doesnt see you anymore
6. you still see that you're tagged (which shouldnt happen in vanilla mc)
7. you wont get hurt by the guardian while out of his vision (this is normal, nothing wrong here)
8. once you move away from the blocks and are back in his vision, the guardian instantly attacks you. In normal vanilla it should tag you again and start counting down till he attacks you.

**Details**

Mobarena version: 0.104.2
Minecraft Server version: 1.12.2

**Additional info**

**Comment by garbagemule** [comment]
Thanks for the bug report!

If I understand correctly, placing a block in front of a guardian that has you on lock should make the guardian "forget" you and not target you anymore.

If that's the case, then there is a good chance it's because of MobArena "re-targeting logic". When a monster changes its target, MobArena will find a new one by locating the closest player. If you are the only player in the arena, it will always be you, but even if you aren't, there is still a chance that it will be you. Can you verify this by having someone else join you in the arena to see if you can make the guardian occasionally switch targets by placing blocks in front of it?

**Comment by Ghmmy** [comment]
Looks like the guardian will still be focussed on the player, while it is attacking the other player as well but without a cooldown.

https://imgur.com/a/Q61OjtF

**Comment by garbagemule** [comment]
Okay that's pretty broken :P

Guess we'll have to really dig into it to figure out the root cause.

**Comment by Ghmmy** [comment]
so I was havinga showerthought.. When the mobs spawn in, they are automatically set to aggressive (take endermen as example, they instantly attack you without looking at them), this means the same for guardians: guardians in their aggressive-state will be set to targeting the player, and when the player is behind blocks, the aggresive-state will disappear in vanilla mc, making the guardian no longer target the player.

What I mean with this is that because Mobarena is setting all mobs to their aggressive-state, guardians wont stop targeting the player because of it. Maybe it could be fixed by only specifying neutral mobs (aggressive in certain conditions. list of the neutral mobs: https://minecraft.gamepedia.com/Mob#Neutral_mobs ) so it wont conflict with mobs that use a different AI, like the guardian in this case.
