### ISSUE TITLE
Using Flat value for health sets the mob to that exact health instead of using the scaling formula

### ISSUE THREAD

**Issue by Jechto** [garbagemule/MobArena#605]
# Bug report
**Short description**

Hi, i've been trying to use custom multipliers for my health scaling but there seems to be an unintended issue.
When i use the values "low","medium","high" etc. The health scales exactly as i should
ie low health with 2 players = (2+1) * 20 * 8 = 480 HP

But if i use a flat value such as "100" i get a mob with exactly 100 HP regardless of scaling and amount of players

It clearly states in the WIKI page that the flat values scale aswell, but they dont seem to

**Reproduction steps**

1. Create a boss, set it's healthmultiplier to one of the enums, i personally used "low"
2. Test boss with both 1 and 2 players
3. Repeat with number aswell waves/WaveParser.class file under the method ParseBossWave, although i'm not sure. Could be spigot version.

**Details**

* **MobArena version**: 0.104.2
* **Server version**: Spigot 1.15.2-R0.1-SNAPSHOT
* **Stacktrace** (if applicable):
There is no stacktrace but i think the problem happens 
in the method ParseBossWave in the WaveParser class

**Comment by garbagemule** [comment]
Hi, thanks for the report!

There is no bug here, however. This is the intended behavior of flat values. Support for them was added because people wanted flat health values that weren't affected by the scaling formula.

Issue #461 is about making the formulas more flexible, so please head on over there and see if you can provide any additional information or thoughts on how we can go about it :)

**Comment by Jechto** [comment]
Well how do you go about setting custom scaling value if you want something with custom multipliers. Is this feature not supported?

**Comment by garbagemule** [comment]
Bingo.
