### ISSUE TITLE
Magicspells dependency issue 

### ISSUE THREAD

**Issue by LucyValeheart** [garbagemule/MobArena#609]
# Bug report

While a player exists and casts spells, mobarena takes the cast event and screams at me about it. (see stacktrace below)

1. Install Mobarena and Magicspells Beta 5 together
2. Attempt to cast a spell
3. Error appears in console/stacktrace in logs

**Details**

* **MobArena version**: 0.104.1-SNAPSHOT
* **Server version**: git-Spigot-1a3504a-84f3da3 (MC: 1.13.2)
* **Stacktrace** (if applicable): https://pastebin.com/X71AVVcB

It appears that, according to the devs in the Magicspells discord, the issue is getCaster() updating from Player to LivingEntity, and mobarena needs to update its hooks.

**Comment by garbagemule** [comment]
It looks like this is a breaking change in MagicSpells 4.0+, but 4.0 is still in beta. It also looks like there's a decent process for releases on MagicSpells, so I think we can definitely prepare for the breaking changes, but I don't want to release a build of MobArena that depends on a beta/development build of MagicSpells.

Perhaps @TheComputerGeek2 or @Chronoken can shine some light on whether or not this breaking change is intentional or if it will be fixed on the MagicSpells end. If it is intentional, we'll have to cut support for older versions to support the new version, and in that case, I'd much prefer it if we depend on a final/release build.

**Comment by garbagemule** [comment]
Just a comment to track the output from the discussion we had on Discord w.r.t. this issue.

The MagicSpells integration is currently very, very limited in scope. All it does is allow for banning spells on swarm waves and boss waves. Because MagicSpells already has a permission check, the same exact effect could be achieved if MobArena permitted wave-local permission attachments.

I'm going to open a new feature request, but I'll leave this issue open until we've decided what to do :)

**Comment by LucyValeheart** [comment]
The integration can be accomplished with magicspells alone and MA without using any of the integration, which means it can easily be scrapped.

Before a swarm/boss wave, add an "upgrade" wave that gives each player an item. Use Magicspells modifiers to make it so that specific spells cannot be cast while that item is in the player's inventory.
After the swarm/boss wave, use another upgrade wave to give a second item, which has a spell that costs both itself and the limiter item. You can use sprint/sneak triggers on a passive spell to make the casting happen without player's needing to input any extra triggers.
