### ISSUE TITLE
/ma random join

### ISSUE THREAD

**Issue by SkyTecDome1994** [garbagemule/MobArena#613]
# Feature request

**Short description**

a Command that make possible to join a random arena who setup rdy

**Implementation details**

it should work with kind like /ma join random 

Just a command who random define a arena

**Additional info**
sry for my bad english..

**Comment by garbagemule** [comment]
We had a bit of a chat about this on Discord. I'm going to just give a quick recap of what was discussed:

- Some people would like a way to pick an arena at random to combat indecisiveness and introduce a level of "random excitement" in the arena picking process.
- Because the arena picking process is instantaneous and "without frills", it is possible to achieve this randomization with a command override style plugin, requiring no code changes in MobArena.
- When/if a queue system is introduced in MobArena, the idea of randomization becomes much more relevant, in that it can create a level of suspense and introduce another layer of rewards (akin to how random dungeons in World of Warcraft work). Until then, the requested functionality remains extremely niche and unnecessary because workarounds are possible.
