### ISSUE TITLE
Elytra not a valid armor piece

### ISSUE THREAD

**Issue by zer0key123** [garbagemule/MobArena#616]
# Bug report

**Short description**

If you have elytra as the chest piece on a class(that was created using a chest lobby), it does not get  added to the user after choosing that class 

**Reproduction steps**

1. Create a chest-based lobby, with a class that uses an elytra as the chestpiece
2. Choose that class
3. All items except elytra get equipped

**Details**

* **MobArena version**: 0.104.2
* **Server version**: Spigot

**Additional info**

**Comment by Nesseley** [comment]
**Other items that should be possible:**
- Banner in head slot. Ex: Can be used to display role without using colored armour.
https://gyazo.com/da50167840a7ea012a3986d26a04deec

- End rod in head slot. I am now a fashionable unicorn. 
https://gyazo.com/15ea789d068fc6fd33a8cbfbb0be74fd

- Turtle shell. This is already a hat in minecraft.

**Comment by garbagemule** [comment]
The head slot is already kinda "fair game" for any item or block and has been for a while. For some reason, Minecraft won't allow you to place e.g. a dirt block in the head slot via the inventory GUI, but we can do it _programatically_.

As for the elytra, we could solve this in one of two ways:

1. Add an "ELYTRA" case to the switch statement that determines where an armor slot goes: [Link](https://github.com/garbagemule/MobArena/blob/c9b36f499398e70e2a2729ddf1d449d11871ce35/src/main/java/com/garbagemule/MobArena/ArenaImpl.java#L1181-L1199). Because "ELYTRA" has no underscores in it, it shouldn't split up the string, and so we can just match it completely.
2. Allow _any item_ to go into _any slot_, and catch the error at runtime. This would mean that MobArena would _try_ to put an item into the chosen slot, and if it fails, we just add it to the inventory as a normal item.

The first way makes this a `good first issue`, because it's very simple and very low impact. The second way is more future proof, but it does require a bit of messing around with try-catch statements around everything, assuming they will actually catch anything for a clean recovery.

**Comment by garbagemule** [comment]
@zer0key123 Please feel free to hop on Discord and grab the latest test build where this fix should be included :)
