### ISSUE TITLE
Arena Delay to Join after finishing

### ISSUE THREAD

**Issue by Brickwrath** [garbagemule/MobArena#630]
**Short description**
A config option to keep the join arena sign disabled for an integer quantity of seconds after the arena is finished.

For example, in config.yml:
`arena-delay: 30`
`#the time in seconds the arena cannot be rejoined after it finishes`

**Implementation details**
The integer listed in the config option `arena-delay` would delay turning on the join sign after the end of an arena by that many seconds.

**Additional info**
When an arena is finished, a configurable delay for the next party to join would make the experience much better.
Currently, the moment another match begins, the scoreboard is wiped and players don't get a chance to see it because other players have already begun another game.  Having the "join sign" disabled for a configurable amount of seconds after the arena is finished would fix this.

**Comment by garbagemule** [comment]
We've previously discussed the idea of cooldowns at great length in #534, and my general take on it is "wrong solution".

However, that discussion is about _per-player_ cooldowns, which are actually entirely different from _per-arena_ cooldowns. In the future, arenas _will_ have cooldowns of sorts, because the Restoration Rework will see to it that restoration happens across multiple ticks to allow for more thorough restoration across the entire region without having to do everything in one tick (which is very laggy for even moderately sized arenas). That's more of a side-effect than an actual motivation for having cooldowns, though.

I think we need to explore _proper_ motivations for having per-arena cooldowns. I don't consider the current motivation _proper_, because the ability for someone to play an arena should not affect the ability for someone else to view the stats of a previous arena session. Those two _should_ be entirely decoupled, but they aren't, and that gives way to the current idea for a _workaround_. I don't think we should implement workarounds for things that the plugin should just do properly. It puts the plugin "at war" with itself, and it hinders further development.

What you are asking for here is, arguably, just a way to "save" the previous session so you can look at it while someone else is playing. We could solve that by having two sets of leaderboard signs, one showing the current session and one showing the previous session. When the current session ends, the previous session boards are filled with the info from the current session, and the current session is wiped. This doesn't "fix" the problem, but it does delay the wiping. It also doesn't allow you to properly keep track of things in the past if you wanted to. For that, we need the Stats Rework.

A workaround you can deploy _right now_ is to simply set a start delay on the arena. The leaderboards shouldn't update until the arena actually starts, and this allows you to effectively have the cooldown you want, except the cooldown "takes place" inside the lobby. It _does_ allow players to pick their classes and ready up, such that when the delay is over, they're ready to go.

If we truly should have per-arena cooldowns, I'm totally open for a discussion about it, but I do think the motivation here is wrong. I hope it makes sense.

**Comment by PrinceOfIonia** [comment]
Perhaps we can add a new command, maybe like `/ma scores (player)` which will show you all the scoreboard info you want to see from your latest MobArena session. Using this command will show you all the leaderboard stats for the player you searched for, so you could see how much damage you did compared to your friends, see what wave they died on, what class did they picked, monster kills, etc etc. 

These 'last session scores' would probably be stored in an memory file that isn't meant to be modified, and when the player finishes (not on start) a new MobArena session, their old scores are replaced with the new ones.

If players are prideful of their leaderboard stats, they could always take a picture of them and save it in a file on their computer. However what would be interesting is if MobArena kept 'High Score' statistics. For example you could do `/ma highscores (arena name)` and it will display a list of the highest statistics achieved in a single MobArena session along with the player who achieved them. This could be stored in another unchangeable memory file so that server owners don't fake high score listings.

The `/ma scores (player)` command would probably have an output looking like this:

[MobArena] Here are `(player)`'s statistics from their last play session
Class: `class`
Last Wave Until Death: `lastWave`
Monster Kills: `kills`
Damage Done: `dmgDone`
Damage Taken: `dmgTaken`
Weapon Swings: `swings`
Weapon Hits: `hits`                                                                                             

The `/ma highscores (arena)` command would probably have an output looking like this:

[MobArena] Here are the highscores of (arena name)
Last Wave Until Death: `(player)` - `lastWave` _[if `final-wave:` is set to a value above 0, do not list this statistic]_
Monster Kills: `(player)` - `kills` 
Damage Done: `(player)` - `dmgDone` 
Damage Taken: `(player)` - `dmgTaken`
Weapon Swings: `(player)` - `swings` 
Weapon Hits: `(player)` - `hits`                                                                                

Perhaps the `/ma highscores (arena)` could be worded a bit better, but that's the general idea of how it should work. 

What are your thoughts on this? Would it help solve your issue @Brickwrath ?

**Comment by garbagemule** [comment]
@PrinceOfIonia like I mentioned in my comment, that would be Stats Rework territory. I'd like to keep this issue specifically about per-arena cooldowns, and if they aren't relevant, we should close this issue. There is a semi-meta stats issue that we can track stats related discussions on: #162

**Comment by PrinceOfIonia** [comment]
You make a fair point! My mistake, seems I got too carried away.

**Comment by garbagemule** [comment]
@Brickwrath Did you close the issue because you found a workaround? If so, would you mind sharing what you did? :)

**Comment by Brickwrath** [comment]
Unfortunately, the more I worked with MobArena the more troublesome it seemed.  Eventually, the problems generated it from (invisible entities, mob tracking, stats not being saved, arena lag/delays, etc) greatly outweighed what it could offer, so we turned to an alternative solution.
Thanks for checking in on it though; I have no doubts y'all will keep working to make this system awesome, it definitely has a lot it can deliver (just not enough for my objectives, unfortunately).

**Comment by garbagemule** [comment]
@Brickwrath That's fair. You're always welcome to return and contribute to the project however you can, be it feature requests, bug reports, or just general feedback. Aside from the lack of persistent stats, the rest of the issues you refer to are new to me, so if you want, I'd be happy to talk about them, either on Discord or on separate issues.
