### ISSUE TITLE
global-join-announce: true is spammable.

### ISSUE THREAD

**Issue by Nesseley** [garbagemule/MobArena#632]
# Bug report

**Short description**
When global-join-announce: is set to true, players can join and leave the arena to spam the arena start announce.

**Reproduction steps**
1. Put global-join-announce: true in config.yml
2. join and leave the arena as many times you'd like. 
3. Have fun spamming! 

**Additional info**
I suggest adding a cooldown on the message per arena that you can edit yourself in the config.

**Comment by garbagemule** [comment]
I wouldn't classify this as a bug. The plugin has no warning labels, but it does what it says on the tin. One could argue that the config setting is the safety valve - it's entirely possible to mute the spam by just turning the setting off.

This is somewhat relevant to both #630 and #534, in that there is some underlying issue about _timing_, and the proposed solution is always cooldowns/delays on a pretty narrow area of the plugin. There are lots of _functional_ reasons to dislike cooldowns (as discussed in #534), but they also make the state of the plugin difficult to reason about, because there's always that extra element of time and not just states and straightforward transitions. This makes developing new features around _joining_ more complex, because there's that timing issue to keep in mind all the time.

In this case, I think a cooldown on the _message_ is the wrong approach, because two people might join two different arenas within the cooldown window, and then only the message from the first arena will be broadcast, even though it is a perfectly legitimate scenario - a false positive. We could make the cooldown per-arena, but then you could just cycle through all arenas and spam that way.

A _short_ cooldown (5-10 seconds tops) on _joining_ is arguably better, because it means spamming requires coordination between multiple people, so it prevents that one guy from being an asshole. This is, however, a very slippery slope towards #534, which argues for much longer cooldowns that would have to be persisted. Personally I'd say this issue is much closer to #630, but people will undoubtedly shoehorn #534 into such a cooldown and then complain about restarts wiping the cooldown state (it isn't necessary to persist short cooldowns, because they will have finished when the server is back up anyway).

There are now references to this issue on both #534 and #630, so let's close this issue and continue tracking the spam aspect on #630, since a short cooldown - whether it's per-player or per-arena - will transitively solve the spam issue as well.
