### ISSUE TITLE
Potions become water bottles in 1.8

### ISSUE THREAD

**Issue by MedicOP** [garbagemule/MobArena#633]
**Short description**
If you add potions to a class either by editing config.yml or using a classchest, upon selecting the class in the MobArena lobby, water bottles are put in the inventory instead of the correct potions.

If you used a class chest, the potions in the actual class chest are also changed to water bottles .

**Reproduction steps**
1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Inventory has water bottles instead of the intended potions

**Details**
* **MobArena version**: 0.104.2
* **Server version**: Spigot 1.8.8

**Comment by garbagemule** [comment]
I think this has to do with the way MobArena makes items unbreakable in 1.8, because the unbreakable flag didn't exist back then. MobArena sets the durability of all items to the highest possible durability the game supports, making items "effectively unbreakable", though not truly unbreakable, since they _will_ break after exactly 32,768 (2^15) hits. MobArena indiscriminately sets the durability of _all_ items, and I believe the durability messes with potions.

Can you try setting `unbreakable-weapons: false` for one of your classes and see if that fixes the potions problem?

**Comment by MedicOP** [comment]
That seems to fix the issue, thanks

**Comment by garbagemule** [comment]
Good to hear! Thanks for helping clear that up. We've had a few people mention this on Discord before, so it's nice to at least have _some_ way to get around it, albeit not a true fix.

I can't promise this will be fixed, because 1.8 support is likely getting phased out unless I find a better way to maintain it. It should be somewhat easy to fix, though, as we can probably just make an exclusion list of item types to skip the durability change for.

The offending line is this: https://github.com/garbagemule/MobArena/blob/80603f0396338f66b72cdb319c25e454c542e5ae/src/main/java/com/garbagemule/MobArena/ArenaImpl.java#L1222

**Comment by XxPermaxX** [comment]
I can't find that setting where did you find it? Trying to use this for my 1.8 server as well and can't seem to find that anywhere. If you can contact me on discord XxPermaxX#7796 Thanks!

**Comment by garbagemule** [comment]
@XxPermaxX it is an optional setting that all classes support, but don't have by default. Check out the Setting up the config-file page on the wiki.

**Comment by garbagemule** [comment]
Fixed in v0.105 :)
