### ISSUE TITLE
MobArena still clears players inventory!

### ISSUE THREAD

**Issue by johananderssonv** [garbagemule/MobArena#635]
**Short description**
I have a multiverse server, and when players leave the arena (with signs or commands) they get teleported back and their inventory gets wiped. I have tried making the rewards cash only, same problem. I've tried grouping the inventories of the mobarena world to the other worlds in multiverse, same problem. I've even tried joining from the same world but it still wipes my inventory.

**Reproduction steps**

(0.) Put something in your inventory for debugging purposes
1. Join an arena with /ma join
2. Hit a sign to pick a class
3. Die
4. type /ma leave or click the sign
5. Get teleported back
6. Lose your items

I'm using the arena called Stone, not Default
[Config.zip](https://github.com/garbagemule/MobArena/files/5045400/Config.zip)

* **MobArena version**: 0.104.2
* **Server version**: Spigot build #120 (Jul 6, 2020 8:31:10 AM)

**Comment by garbagemule** [comment]
Hiya, please use Discord for support questions like this :)

The issue is not with MobArena, but with the plugin handling multiple inventories. You can solve the issue by configuring your multi-inventory plugin such that it either _synchronously_ loads inventories _early_ in the event cycle (PerWorldInventory works fine in that regard) or doesn't swap inventories at all. MobArena does exactly what it is supposed to: it stores and then clears your inventory when you join, and it clears and then restores your inventory when you leave. The problem is that the plugin handling inventories arrives at the party too late.

**Comment by johananderssonv** [comment]
Thanks for the quick response! I've opened a ticket on multiverse-inventories. :)
