### ISSUE TITLE
Netherite armor wont equip automatically

### ISSUE THREAD

**Issue by Poweringg** [garbagemule/MobArena#636]
# Bug report

**Short description**
Netherite armor wont equip automatically, when player picked class in lobby.

**Reproduction steps**

set config like this - https://pastebin.com/Jr52qXpp

1. Join an arena with /ma join
2. Hit a sign to pick a class
3. netherite armor wont equip automatically like diamond, iron etc.

**Details**

server: PAPER, 161 1.16.1
MobArena: 0.104.2

**Additional info**

**Comment by garbagemule** [comment]
Thanks for the bug report.

I just want to clarify a few things:

- This is _only_ a problem when using the generic `armor` node in the config-file.
- Using the slot-specific nodes in the class definition works (because they invoke prefix-specific thing parsing).
- Using class chests works (because they look at the suffix, e.g. `_CHESTPLATE`).

We probably can't really fix this before bumping to the 1.16 API using the current approach, since these new armor pieces don't exist in 1.13. There is of course the possibility of consolidating the [behavior of class chests](https://github.com/garbagemule/MobArena/blob/b0969c655c2d78d18fe71ecd035ec3e4b60e47dc/src/main/java/com/garbagemule/MobArena/ArenaImpl.java#L1146-L1233) and the [behavior of the generic armor node](https://github.com/garbagemule/MobArena/blob/b0969c655c2d78d18fe71ecd035ec3e4b60e47dc/src/main/java/com/garbagemule/MobArena/things/Equippable.java#L62-L77), which would make things a little more consistent.

Another option is to just deprecate the generic `armor` node and update the default class definitions to using the slot-specific nodes. I honestly don't think the comma-separated list of items is doing anyone any favors. The explicit lists and slot-specific nodes in the config-file are much more clear and much more predictable.

**Comment by garbagemule** [comment]
@Poweringg I think consolidating the behavior is the way to go. I have a build ready for you on Discord if you want to help test it out - just ping me :)

**Comment by PrinceOfIonia** [comment]
Just tested the most recent build and can confirm it works now, however the spectator warp is now bugged so I recommend waiting until that is fixed before you update.
