### ISSUE TITLE
Pillagers do not attack.

### ISSUE THREAD

**Issue by MrJwhat** [garbagemule/MobArena#641]
Whenever a Pillager spawns, it spawns with the weapon but does not attack.

1. Create an arena
2. Setup Pillager spawn

Mob ArenaV:0.104.2

**Comment by garbagemule** [comment]
It looks like the problem is that pillager crossbows are cleared on spawn just like all other equipment.

To properly fix it, we need the API version to be high enough to "know" crossbows, which 1.13 doesn't. This means that we either need to bump to 1.14+ (when pillagers were introduced) or I need to wrap up and commit to my "one build" rework that has support for 1.8, 1.12, and 1.13+ in it. Then we can bump to 1.16 and add an extra 1.13 and/or 1.15 layer or something.

Just gonna mark this as dependency blocked and get back to it when I have the "one build" rework wrapped up.
