### ISSUE TITLE
MC scoreboard death counter raises after every arena participation

### ISSUE THREAD

**Issue by DeathDragonAW** [garbagemule/MobArena#642]
I have set up a deathCount score on my server which now interferes with the mobarena. Some people don't like their 0 stat to change by using the arena e.g., is there any way to fix this?

**Comment by LucyValeheart** [comment]
temporary solution: set up a reward wave round 1 that runs a scoreboard command to reduce the deathCount by 1

**Comment by Nesseley** [comment]
Well yes, but then you can join the arena. Get 1 less death, and leave without dying /ma leave and spam that to get less deaths.

**Comment by garbagemule** [comment]
There is no feasible way to prevent this because when you die, you die. It's entirely possible to get around it with a Skript or something that listens to MobArena's events and responds to the player death event.

The workaround with a command reward will work if you also remove the `mobarena.use.leave` permission, which forces players to play and die in the arena.

Honestly, this seems like something a different plugin should solve. Perhaps a multi-world plugin can disable stats in a specific world and you could put the arena(s) in that world. Deaths are not the only stat that MobArena sessions manipulate. I don't think it's feasible to block it all.

**Comment by DeathDragonAW** [comment]
Thx for all the replies!

> The workaround with a command reward will work if you also remove the `mobarena.use.leave` permission, which forces players to play and die in the arena.
Not possible within mobarena as far as I see?

**Comment by garbagemule** [comment]
@DeathDragonAW Just revoke the permission from all classes as demonstrated in the example: https://github.com/garbagemule/MobArena/wiki/Setting-up-the-config-file#per-class-permissions

Gonna close the issue since I don't think this is something we should do anything about. If there really is no way around it, then if anyone has an idea as to how we can circumvent the death toll (heheh), we can re-open. An example of an open source minigame plugin that actually deals with this would make for a much more solid case, but I've never heard about this before.

**Comment by DeathDragonAW** [comment]
> temporary solution: set up a reward wave round 1 that runs a scoreboard command to reduce the deathCount by 1

`    rewards:
      waves:
        every:
        after:
           '0': cmd:/scoreboard players remove @p Tode 1`

Tried it this way, but it works not properly as this just chooses the nearest player. @s is doing nothing and the other target selector options seem even less promising.

**Comment by garbagemule** [comment]
Use the player variable as demonstrated in the examples on the syntax page.
