### ISSUE TITLE
If the plugin starts before a world is loaded, the signs.data wont load.

### ISSUE THREAD

**Issue by Hybes** [garbagemule/MobArena#645]
**Short description**

When the server starts, MobArena often always starts before Multiverse, so the signs.data tries to establish connection to a sign in a world thats not loaded.

**Reproduction steps**

1. My scenario used Multiverse, but it most likely occurs with other world management plugins. (perhaps plugins are loaded alphabetically?)
2. Set up a normal, functional arena.
3. Restart server
4. The server then loads MobArena first, before the world loads.

**Details**

https://pastebin.com/ux1qqmvH

* **MobArena version**: 0.104.3-SNAPSHOT
* **Server version**: Paper-1.26.3-v215

**Additional info**
N/A

**Comment by garbagemule** [comment]
I had an idea for dealing with this problem with a sort of "best effort" approach of naively parsing everything as we do right now, but in case of a failure, retry after a few seconds. This should catch all the cases of race conditions at least. 

The trouble is, however, that the error thrown from deep inside of Bukkit and SnakeYAML never actually makes it all the way up to MobArena, because in Bukkit, the error is [simply logged](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/configuration/serialization/ConfigurationSerialization.java#93-96) and everything continues as if nothing happened. This means that MobArena _cannot detect that there is a problem_, so it has to assume that everything is peachy. What a mess 😞 

I have decided to leave this issue for now and focus on getting 0.105 out, since fixing this problem (which also appears to be an issue with class chests) might require making some breaking changes. Due to the slug identifier rework in 0.105, there will already be breaking changes w.r.t. permissions, so I'd rather just roll that out first and give people an easier time updating than having to fix a bunch of different things.
