### ISSUE TITLE
MyItems permission does not work

### ISSUE THREAD

**Issue by Kbryst** [garbagemule/MobArena#647]
**Short description**

MyItems permission doesn't work.

**Reproduction steps**

I cannot negate the permission to the class "myitems". In luckperms it auto fills with a space in the permission to show "my items" instead of "myitems".

Tested on both paper 1.12.2 and 1.16.3
MA 0.104.2

https://ibb.co/X4SjNNX
https://ibb.co/GCB7Z6Q

**Comment by garbagemule** [comment]
Thanks for the bug report!

To be clear, the permission for the My Items class ought to be `mobarena.classes.myitems`. Chances are this affects _all_ classes with spaces in the names. Because My Items is an _implicit_ class, there is no way to fix the underlying issue as a server owner by renaming the class.
