### ISSUE TITLE
Class Chests reseting after mob arena reload.

### ISSUE THREAD

**Issue by arbiterthedog** [garbagemule/MobArena#651]
# Bug report

**Short description**

When I update my config files and reload mob arena through the in-game command, if I choose a class which was linked to a global chest, instead of getting the items in hand... I recieve nothing. This means I have to set the chest back for every one of the classes every time I reload the plugin. 

**Reproduction steps**

Update a config file
Reload plugin through /ma reload
join a map and select a class (that is linked to a global classchest)

**Details**

* **MobArena version**: 0.105 (1.8 edition)
* **Server version**: Spigot 1.8.8 eab41

**Additional info**
Not really

**Comment by garbagemule** [comment]
Thanks for the bug report!

I can't reproduce this on 1.16, so I'm guessing whatever problem there might be is isolated to 1.8, which unfortunately puts it at the way bottom of the issue pile, since 1.8 support is being phased out.

However, it might just be an issue with world load order or file handles. Try the following:

- Close all editors and open file handles to the MobArena config-file.
- Stop your server.
- Open the config-file in a text editor.

If the class in question _doesn't_ have a `classchest` property with a valid location, it could be that something is preventing MobArena from writing to its own config-file, or the config-file is overwritten due to manual edits _after_ MobArena has already stored the location. You must reload the config-file in your editor after any setup commands of any kind, because otherwise you'll be overwriting what changes MobArena is making itself. Close the text editor, start the server back up, link the class chest, then stop your server and open the config-file and check again.

If the class _does_ have a `classchest` property, try spinning up the server again and see if it works now. If not, post the startup log and your config-file on pastebin and link them here.

**Comment by arbiterthedog** [comment]
So upon messing with it for a bit, I have realized what the issue is. The copy of the config file I had was before I added the classchests so every time I added them, I would go and edit the config file with the copy of which I had which meant that like you said, it wasn't saved. This wasn't a bug and it was an error on my side. Apologies.
