### ISSUE TITLE
MA breaks on paperspigot update

### ISSUE THREAD

**Issue by slvlr** [garbagemule/MobArena#660]
# Bug report

**Short description**
I updated my paperspigot version to 1.16.4 build 356 (was previously on 354).
And then Mob arena stopped loading.

* **MobArena version**: 0.105
* **Server version**: Paperspigot 1.16.4 build 356
* **Stacktrace** : https://pastebin.com/Q8gkR4VU

**Comment by garbagemule** [comment]
There's no such thing as "paperspigot".

It doesn't look like this has anything to do with the update you made. If it _is_ because of an update, it's due to a breaking change or bug in Paper, but it looks more like this is related to #645.

Feel free to reopen if it is not related, or if MobArena actually doesn't work on the latest Paper build in a clean setup. Otherwise, please hop on Discord for support with your setup :)
