### ISSUE TITLE
Problems with sign states

### ISSUE THREAD

**Issue by MaksyKun** [garbagemule/MobArena#673]
# Bug report

**Short description**

When I use the arena signs, they keep staying in there state. For example my sign-config looks like this:

```
info-idle:
- '&6◆ &6Info &6◆'
- '&f-'
- '&bWaiting for'
- '&bplayers'
info-joining:
- '&6◆ &6Info &6◆'
- '&f-'
- '&bPlayers: &a<lobby-players>'
info-running:
- '&6◆ &6Info &6◆'
- '&f-'
- '&bWave: &a<current-wave>'
- '&b✔: &a<live-players>/<initial-players>
```

But if you start the arena, it keeps staying in 'info-idle'. I also looked the wiki up and restarted the server several times.

**Reproduction steps**

1. Place an arena-sign
2. Reload the plugin/ Restart the server to get sure its not this
3. Start and enter the arena
4. Look at the sign, it should be the same state as it was before (in this case -idle)

**Details**

* **MobArena version**: 0.106 (real version) + 0.106 (with self implemented methods)
* **Server version**: Paper (newest Version afaik)
* **Stacktrace** (if applicable): There are no errors at all

**Additional info**

If it should be clear from the MobArena version: I implemented a tiered Method and other small stuff to our server. To make sure it's not my fault, I deletet this version onced and downloaded the original version. It still appears there.

**Comment by garbagemule** [comment]
Hey Maksy,

I just ran a quick test on a Spigot 1.17 server with MobArena 0.106 from Spigot, where I added three info signs, and they are working as expected, changing based on the state. I also stopped and started the server back up and tried again, and MobArena reported loading the three info signs I created.

Maybe your sign data files got corrupted or didn't get migrated correctly in the 0.106 update? You can try digging around in the `data/signs.csv` file, or you can just delete it and re-create the signs. Unless MobArena specifically reports that it has loaded X sign(s) during startup/reload, the signs "don't exist".

I'm gonna close the issue because the signs are working fine when set up correctly. If there is indeed a bug, feel free to reopen, but otherwise just hop on Discord and we can take a look together.

Cheers,
mule
