### ISSUE TITLE
mobarena.admin.teleport doesn't remove a warning?

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#702]
# Bug report

**Short description**

When I tp to the player that currently playing in arena using spectator mode, I see the warning in chat that says "u can't tp to player in arena" or something similar. But I have `mobarena.admin.teleport` permission and tp works anyway.

**Reproduction steps**

1. Teleport to any player that currently playing in arena using spectator teleport menu (middle mouse button) and with `mobarena.admin.teleport` permission
2. Warning appears in chat, but u will be tpd anyway

**Details**

* **MobArena version**: I currently don't have access to server logs and can't tell this.. I have access to console, but I can't find command like `ma version` :c
* **Server version**: Paper 1.16.5

**Additional info**

Currently I'm very far from home and can't give some information, but I think that this issue is still valid and I will try to help if you need

**Comment by Nesseley** [comment]
All plugins show their version if you use `/ver <plugin>` and server version you can find by using just `/ver`

**Comment by molor** [comment]
Oh sorry I forgot about this
```
MobArena version 0.104.3-SNAPSHOT
```

**Comment by Nesseley** [comment]
0.106 is the newest version, I recommend that you update to get fixes and new features :)

**Comment by molor** [comment]
I can't do it now because I'm far away from home in next 1-2 weeks. Sure that I update it ASAP, but if u can check this in the last version and confirm that this problem is still exists, so that we do not have to wait these 1-2 weeks, I would be very grateful

**Comment by molor** [comment]
Same on 0.106, so 2 weeks of waiting, as I said, was wasted

**Comment by garbagemule** [comment]
Thanks for confirming that it's an issue on 0.106. It's definitely easier for you to confirm it, since you don't have to _try_ to reproduce it. No time wasted :)

I had a quick glance through the source code and the message is harmless. It might require pulling up some nasty stuff by the roots to fix it, though, so I don't think a fix will make it into 0.107. But like I said, it's harmless. As a workaround, you could just disable the announcement all together if it's too annoying.
