### ISSUE TITLE
Pets are not removed on player death

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#721]
# Bug report
(self-explanatory)

**Reproduction steps**
1. Join the arena with spectate area set
2. Select class with pets (wolves in our case)
3. Die
4. See that pets are still near you

**Details**
* **MobArena version**: https://github.com/garbagemule/MobArena/actions/runs/1835158985
* **Server version**: Paper 1.18.1

**Comment by molor** [comment]
I'm too lazy for creating yet another issue for feature request, but I think that setting like `remove-pets-on-player-death` would be also useful in this issue.

**Comment by garbagemule** [comment]
Pets are supposed to be removed on player death, so that's probably the actual bug here. Please either close this issue and create a new one, or edit this issue to reflect the bug that pets remain in the arena after their owner has died.

As for being too lazy to create feature requests separate from bug reports, that's just how it has to be, sorry. Each issue addresses one bug _or_ one feature, but never both, and never more than one. Think of it this way: the more stuff you cram into one issue, the more complex it becomes, the more time and effort is needed from everyone, and the less likely it is to ever be addressed. It's in everyone's best interest to break things down into manageable, coherent pieces 🙂

**Comment by molor** [comment]
wow, thanks for fast reply о:
okay, I will create a new issue/FR for you, you're really a good dev

**Comment by molor** [comment]
this.notifyAboutUpdate(UpdateStatus.DONE)

**Comment by garbagemule** [comment]
@molor I can probably get this fixed for the release, but I don't have a good way to test it out because it kinda requires at least two players (one with a pet who dies and one to stay in the arena). Would you like to help test out a possible fix? If so, I can either provide you with a build directly on Discord, or I can start a new branch for you to build a jar from.
