### ISSUE TITLE
Add `remove-armor-percentage` for mobs

### ISSUE THREAD

**Issue by molor** [garbagemule/MobArena#723]
# Feature request
I forgot about this yesterday..

**Short description**

Currently, any mob armor is removed on mob spawn.
I think that this can be made customizable.

**Implementation details**

Add setting like `remove-armor-percentage` that defaults to `100` % (to keep old behavior — remove any armor), that specifies the chance (0..100) of removing mob's armor if they have it. This will NOT give random armor to the mob, this will remove this random armor with specified percentage if the server "decided" to give it to the mob during spawn.

In our case, this can make the fight more diverse, mainly due to the fact that dozens of zombies will not look the same.

**Comment by Nesseley** [comment]
Pretty sure this should be a feature for the rework. I remember some talk about making it possible to spawn armor on monsters after the rework, and it would make sense to just implement a % chance then for armor.

**Comment by molor** [comment]
No need to add armor to unarmored entity, noo
> This will NOT give random armor to the mob

Just replace this line https://github.com/Maroon28/MobArena/blob/master/src/main/java/com/garbagemule/MobArena/waves/MACreature.java#L95 with something like `if (Math.random() > remove-armor-percentage) e.getEquipment().setArmorContents(NO_ARMOR);`

**Comment by garbagemule** [comment]
While customization _can_ be great, this sort of hyper-specific behavior fixed in all dimensions except for randomness is not a very useful manifestation of the concept. There is zero room for actual customization, and I can't see this being used as anything but "on" or "off", whatever those states might mean, especially because even in the "on" state, where monster armor isn't removed, it's still completely random if monsters get armor or not.

I'm gonna close this in favor of #351, but it's worth keeping the idea of randomization in mind for the Mobs Rework.
