### ISSUE TITLE
 MobArenaStats plugin error

### ISSUE THREAD

**Issue by samparotony228** [garbagemule/MobArena#746]
# Bug report

**Short description**
I use the MobArena plugin and MobArenaStats (versions: https://imgur.com/a/FzYfw4c), when I selected a kit- went into the arena, killed a few mobs and wrote the /ma leave command, then I get this error in the console. (errors: https://imgur.com/a/PGyTvl1). I found the reason for which parameters in the plugin config this error appears. When this parameter is enabled 
 (parameters in MobArena > config.yml: https://imgur.com/a/iUNF2YZ).

**Reproduction steps**
When the setting in MobArena > config.yml is "auto-ready: true" and after arena battles, use the "/ma leave" early exit.
3. Error appears in console

**Details**
* **MobArena version**: 0.107
* **Server version**: purpur-1.19.2-1774
* **Stacktrace** (if applicable): https://pastebin.com/YpW3nfWP

**Additional info**
MobArenaStats: 1.0 (lasted)

**Comment by garbagemule** [comment]
Hi @samparotony228, thanks for the bug report, and sorry for the radio silence.

I'd say that this is actually a MobArenaStats bug, but it turns out that MobArena doesn't actually fire the ready event that MobArenaStats depends on for setting the "ready time" property. The [logic](https://github.com/garbagemule/MobArena/commit/db953285c5f1e4997887b0110d9b9dac2c906934) that omits that behavior is almost a decade old and doesn't actually come with any explanation as to why there's a distinction when the auto start timer is currently running or if it's "at zero".

If you're still interested in a fix for this, I can make an experimental build that removes the discrepancy in MobArena to see if that fixes the issue. If so, please hop on Discord and ping me :) I could also try to work some more resilience into MobArenaStats instead.
