### ISSUE TITLE
Obsidian Bomb skill damages other mobs even if monster-infight is set to false

### ISSUE THREAD

**Issue by fireheart3911** [garbagemule/MobArena#759]
# Bug report

**Short description**

Obsidian Bomb skill damages other mobs even if monster-infight is set to false

**Reproduction steps**

1. Have a boss with the obsidian-bomb skill
2. set monster-infight to false
3. The bomb still damages other mobs

**Details**

* **MobArena version**: latest (0.107)
* **Server version**: Paper 1.19.2 latest
* **Stacktrace** (if applicable):-/-

**Additional info**

This might also apply to living-bomb and could be related to #758

**Comment by garbagemule** [comment]
Thanks for the bug report!

(_almost_ a copy/paste from #758)

It might be possible to change the [method](https://github.com/garbagemule/MobArena/blob/00605b54f9674ac47b18eb7db1da83071c61bdc0/src/main/java/com/garbagemule/MobArena/waves/ability/core/ObsidianBomb.java#L58) in the obsidian bomb logic to [a different method](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/World.html#createExplosion(org.bukkit.Location,float,boolean,boolean,org.bukkit.entity.Entity)) that has an Entity _source_, which will make the [entity damage by entity logic](https://github.com/garbagemule/MobArena/blob/00605b54f9674ac47b18eb7db1da83071c61bdc0/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L653-L669) run (if we're lucky), so that the _damager_ is handled like an [arena monster](https://github.com/garbagemule/MobArena/blob/00605b54f9674ac47b18eb7db1da83071c61bdc0/src/main/java/com/garbagemule/MobArena/ArenaListener.java#L790-L793), in which case it would just be handled like any other monster-to-monster damage.

If I make that little change and threw it up on Discord, would you be interested in testing it out?

**Comment by fireheart3911** [comment]
Sure, just ping me
