### ISSUE TITLE
Custom Position for /ma leave

### ISSUE THREAD

**Issue by dandud100** [garbagemule/MobArena#760]
# Feature request

**Short description**

We should have the possibility to setup the exit point for /ma leave, as i have a command portal at spawn and it is anoying that players that enter the arena trough this portal will all be in it after they leave the arena. 

**Implementation details**

Could be set per arena like the exit point.

**Additional info**

Nothing. 👍

**Comment by garbagemule** [comment]
This is what the [exit warp](https://github.com/garbagemule/MobArena/wiki/Arena-Setup#about-regions-warps-etc) does 🙂

**Comment by dandud100** [comment]
> This is what the [exit warp](https://github.com/garbagemule/MobArena/wiki/Arena-Setup#about-regions-warps-etc) does 🙂

Then it does not work for me. I used the automatic generated arena and added the exit warp manually to it, but it still teleports me right into my portal.

One thing I also found out is, that after I die in the arena, the be on top of it, I will not die when I jump into the void but fall endlessly.

**Comment by garbagemule** [comment]
Ah, right. So the way the exit warp works is by teleporting the player to the exit warp _after_ the normal leave procedure has run its course. This may seem unnecessary, but the join/leave procedure has a long, bug-ridden past, and the [current implementation](https://github.com/garbagemule/MobArena/commit/b1c6b618279fd181799aeafdb041ad2d1775a585) was an attempt at fixing all causes of inventory-related issues by very meticulously ordering the steps in a way that would, in all reasonable cases, play nice with multi-inventory plugins.

Because exit warps can be "wherever", short-circuiting the process and _not_ teleporting the player back to their join location would break the "promises" of the procedure, possibly re-introducing inventory-related bugs for people who have the exit warp in a different world.

We could perhaps experiment with the idea of world-aware logic, where if an exit warp is set, the warp back to the join location only happens if the exit warp is in a different world. It does feel like something that should be configurable, though, since the process is quite brittle and might break someone else's setup if changed.

I think your best bet is to find a workaround of sorts. Perhaps whatever portal plugin you use supports some sort of delay or a multi-step process. If the player is first teleported to a different location, for example your desired exit location, and then immediately afterwards, maybe in the next tick, the join command is invoked, that would remove the need for the exit warp and make the whole thing work for your use case. I'm just spitballing here, and I don't actually know much about server setups, but feel free to join the MobArena Discord server and ask for help with this. Perhaps someone else has a few tips :)

**Comment by dandud100** [comment]
So yeah, the exit warp work now as expected, after i restarted the minecraft server. I think the MobArena plugin just didn't loaded the config itself after i added the exit warp with the ingame tool.
