### ISSUE TITLE
Issue: Mobs in arena can't be teleported 

### ISSUE THREAD

**Issue by LexPolka** [garbagemule/MobArena#762]
# Feature request
Allow Mobs to be able to be teleported in arena

**Short description**
Mobs currently aren't affected "/tp". I understand this is to solve the issue with the enderman teleporting out of the arena, however,
it should only be endermen-exclusive or provide an option to enable/disable this feature.

**Implementation details**

One method is to have a new setting, allow-mob-teleporting, similiar to the allow-teleporting setting.
Effects:
This allows all mobs to be teleported within the arena but not outside, so endermen still stay in.

**Comment by garbagemule** [comment]
Thanks for the feature request!

The monster teleport prevention was indeed [originally implemented](https://github.com/garbagemule/MobArena/commit/fba31d26a4139148d3dea599e950652c1888614d) to prevent endermen from teleporting in and out of the arena for obvious reasons.

Writing logic specific to individual entity types has always been a bit of a nightmare because the game evolves and the API is somewhat volatile. Adding a per-arena setting that provides a means of overriding the "within arena region" decision and allowing it to happen is probably the best bet.

**Comment by LexPolka** [comment]
i hope it gets implemented some day! thanks for reading it mules
