### ISSUE TITLE
Maps destroyed within Mob Arena sessions are not restored

### ISSUE THREAD

**Issue by 4729** [garbagemule/MobArena#763]
# Bug report

**Short description**

Random errors occurred and destroyed maps were not automatically restored, even though protection, soft restore, and soft restore drop were set to true in the arena. Also, when this error occurs, the active arena is automatically disabled as "Arena not enabled".

**Reproduction steps**

1. Join the Arena
2. Play longer than 10 rounds
3. During play, players break blocks, break blocks with TNT, Creepers, Obsidian Bombs, or pick up items from chests.
4. Player dies or leaves or clears the arena
5. When exiting, "Could not pass event BlockExplodeEvent to MobArena v0.107" or "Task #147906 for MobArena v0.107 generated an exception" or "Could not pass event PlayerDeathEvent to MobArena v0.107" occurs
6. Part of the map has been restored, but most of it has been destroyed, and items in chests that players have collected are missing. And the arena will be disabled.

**Details**

* **MobArena version**: 0.107
* **Server version**: git-Paper-448
* **Stacktrace** (if applicable): https://pastebin.com/uyr8x5S7, https://pastebin.com/Zj4Qsyt0, https://pastebin.com/t1MB9FSr

**Additional info**

**Comment by garbagemule** [comment]
I think we need a bit more info here. There are two errors at play:

- NullPointerException thrown [here](https://github.com/garbagemule/MobArena/blob/15a79bdd7e26124d1f40b34d4f0043e20612a816/src/main/java/com/garbagemule/MobArena/repairable/RepairableAttachable.java#L19) when MobArena tries to get the "attached face" of an "Attachable" type.
- IllegalArgumentException thrown [here](https://pastebin.com/Zj4Qsyt0) when MobArena tries to restore the contents of a container that it has taken a snapshot of when the arena started.

For the first problem, please try to identify the specific "Attachable" block that causes the issue. This could be stuff like paintings or signs or something like that. It seems odd that the server doesn't resolve an "attached face" when asking an "Attachable" type for the face it is attached on. It could very well be a server bug. It could also be that you have an "Attachable" somewhere unorthodox. Please pastebin your config-file, or at the very least the coords section for your arena.

For the second problem, you have some registered containers in the arena that don't seem to follow the API specification (or perhaps it is due to a deeper rooted issue with the restoration code). MobArena takes a snapshot of its contents prior to starting the arena, and when it tries to restore them, the server claims the given size is wrong, even though the size came from that very container. Please identify all the registered containers in your arena and their specific types so we know what is causing it.

It might be that these are two entirely separate issues, in which case we may need to split this issue up, but let's see when we get some more relevant info.

**Comment by 4729** [comment]
Here is the MobArena Config file. If your container has a large chest, you may have specified two blocks as a container, or you may have specified the same container multiple times, forgetting which one specified it. If it's container related, maybe that's the cause?
https://pastebin.com/ZMC24qLm

**Comment by garbagemule** [comment]
Hi again, and sorry for the lack of attention.

Thanks for posting the config-file! And wow, that is _a lot_ of containers... It is perhaps a bit of a chore to identify all of them 😅 I do think you're right about multi-block containers potentially being a source of the IllegalArgumentException. Could you try _deregistering_ the multi-block containers in your arena to see if that solves that specific error? You may have to deregister both sides of the containers to be absolutely sure. Then, if that solves the problem, you can try re-registering them, but only with one side of the container. If that reintroduces the problem, I'm afraid multi-block containers simply aren't supported.

As for the attachables, I'm a bit stumped, I'll be honest. I could add a null check, but I'm not sure what the "else" part should do if the ”then" part is the one that actually registers the block for restoration - just let it break? In all honesty, though, I think this might be a can of worms that will eventually lead to a "can't fix" scenario where we'd have to revamp the entire restoration portion of the code base (I think there are better solutions to that specific problem, though, which may be worth looking into first). I see lots of TNT in your classes and soft-restore is obviously enabled. I think if you want a quick "fix", just disabling soft-restore will prevent the errors from happening, but if you want soft-restore, you may have to simplify your arena somewhat and try to avoid "special" blocks, which is of course a bit of a bummer.

If you have any region copy/paste plugin installed and know how to use it well, perhaps you'd be interested in trying to replicate the soft restore functionality via command hooks in MobArena? We could take an initial stab at #678 by introducing pre-start and post-end events to execute commands for, and you could set up some copy/paste commands for your region management plugin in those hooks. If it's something you'd be up for, hit me up on Discord and let's see if we can play around with it a bit.

**Comment by 4729** [comment]
Sorry, I overlooked this because the opportunity to open GitHub is not very common for me.
By replacing all the chests in the arena with barrels, and replacing all the signs and lanterns and other blocks with different blocks, I no longer get this error. The error has not happened for a while after doing this
