### ISSUE TITLE
Economy rewards don't work using Denizen script plugin for economy

### ISSUE THREAD

**Issue by Josh65-2201** [garbagemule/MobArena#797]
# Bug report
**Short description**

Other plugins and vault can detect and use this fine but mob area doesn't. Not that it seems to loaded before Denizen from console messages

**Reproduction steps**

1. Enable encomy rewards in area
2. Use denizen as the economy provider
   1. https://github.com/DenizenScript/Denizen
   2. Put the below in the Plugins/Denizen/scripts
   3. [economy.txt](https://github.com/user-attachments/files/16421025/economy.txt)
   4. Rename .txt to .dsc
3. See console message that no economy plugin is installed

**Details**

* **MobArena version**: 0.108
* **Server version**: Paper 1.20.6 build 148

**Comment by garbagemule** [comment]
Completely missed this issue, sorry.

I think this ties back to an old issue with how Vault was designed and how the plugin load order works. The underlying problem is that Vault service registrations work in two ways; either the services are registered as an internal part of Vault while it's loading, or they are registered via Vault's external API _after_ Vault itself has loaded. Any economy service registered _during_ Vault's own load process are available immediately after Vault has loaded, but if they are registered _after_ Vault is loaded, there is no way of knowing when it is safe to reach out for an economy service, because it could be registered in the next tick or in a thousand years.

In order to interface with Vault's API, MobArena loads _after_ Vault. However, MobArena also _extracts_ an Economy instance at load time, which means if one isn't available when MobArena asks, it assumes there never will be. When Denizen or its Economy service eventually loads, probably after MobArena, it's too late.

Previous proposed solutions have been about fragmenting MobArena's own bootstrapping logic, but that's a terrible solution to a problem that really should be solved by a more fine-grained load system. What we _can_ do, however, is create an abstraction for MobArena to use everywhere, and then make that abstraction _lazily_ retrieve the Economy service when needed. This poses two problems we'd need to address:

1. **Caching:** Is it necessary to cache the lazily retrieved Economy service, or is it sufficient to just retrieve it on every call to any Economy-related task? This is probably best decided by hard data, and it would be awesome if the community could contribute here, since I don't have a realistic setup to benchmark on. If we do end up caching, we need to _invalidate_ the cache somehow. If it's possible to do it as part of `/ma reload`, that would be ideal.
2. **Error handling:** The nice thing about the current solution is that server owners are immediately informed about potential issues with economy rewards before a session even begins. It would be annoying to see such a message for every single economy action (imagine 8 players getting 17 economy rewards each, and only when they are eventually attempted paid out, you'd see 136 log messages about economy rewards not working). But perhaps it's the better option. Another option could be to "crash" if economy rewards don't work, or to maybe log specifically what amount was attempted given/taken and to/from whom. That would give server owners a means of compensating players if stuff doesn't work. A third option could be to introduce a sort of "status" or "debug" command that could print out the current "state" of MobArena's internals to help server owners check if stuff is as expected.

**Comment by garbagemule** [comment]
@Josh65-2201 I've been trying to get a server with Denizen to work for 20 minutes now, and I'm not sure exactly what kind of setup I need for it to work, but I don't want to spend any more time on it. However, I've taken the liberty of just running with caching and logging for error handling (addressing the two points above), and I have a build that at least works with BetterEconomy (first economy plugin I found on Google), but I think it might be natively supported in Vault, so it isn't very conclusive, other than "I've rewritten a bunch of code and it still works the same as before". I'm going to push my changes to a new branch if you want to grab a build from GitHub Actions, or you can hit me up on Discord and I'll send you it :)

**Comment by Josh65-2201** [comment]
Here a working server, Trying using the actions build and there no change to this issue
https://1drv.ms/u/s!AhxyZFeyfhCxgpkOUXYpsQi310LPBQ?e=1IqbFR

**Comment by garbagemule** [comment]
It doesn't look like the build used in this zip-file is the right one. It still prints the "Economy rewards will not work" message, and that message has been removed in the refactor. Here's a [link](https://github.com/garbagemule/MobArena/actions/runs/10443890183) to the build related to this specific commit. When I replace the MobArena jar in the test server with the one from GitHub Actions, it doesn't print the message, but I have no idea if the integration is working. None of my attempts at interfacing with the economy provider via commands (`/eco` `/economy`, `/balance`, etc.) bear fruit, so I don't really know how to proceed from here.

**Comment by Josh65-2201** [comment]
All good, I will try the correct build. you can also type `/ex narrate <player.money>` to read the players balance

**Comment by garbagemule** [comment]
Thanks!

I made the fatal mistake of editing the rewards section of the wrong arena, so I wasn't getting the rewards I thought I should, but it seems to be working when I'm not making human errors 😛 At least, the `/ex narrate <player.money>` command is reporting a bunch of stuff and a number that matches the rewards I configured!

**Comment by Josh65-2201** [comment]
Great I will try it out to make sure

**Comment by Josh65-2201** [comment]
Yes it working for me, thank you
